/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SpeakV1Text {
    /** Message type identifier */
    type: "Speak";
    /** The input text to be converted to speech */
    text: string;
}
