/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SpeakV1Close {
    /** Message type identifier */
    type: SpeakV1Close.Type;
}

export namespace SpeakV1Close {
    /**
     * Message type identifier
     */
    export type Type = "Flush" | "Clear" | "Close";
    export const Type = {
        Flush: "Flush",
        Clear: "Clear",
        Close: "Close",
    } as const;
}
