// This file was auto-generated by Fern from our API Definition.

export interface SpeakV1Clear {
    /** Message type identifier */
    type: SpeakV1Clear.Type;
}

export namespace SpeakV1Clear {
    /** Message type identifier */
    export const Type = {
        Flush: "Flush",
        Clear: "Clear",
        Close: "Close",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type] | string;
}
