// This file was auto-generated by Fern from our API Definition.

export interface SpeakV1Flushed {
    /** Message type identifier */
    type: SpeakV1Flushed.Type;
    /** The sequence ID of the response */
    sequence_id: number;
}

export namespace SpeakV1Flushed {
    /** Message type identifier */
    export const Type = {
        Flushed: "Flushed",
        Cleared: "Cleared",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type] | string;
}
