/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SpeakV1Warning {
    /** Message type identifier */
    type: "Warning";
    /** A description of what went wrong */
    description: string;
    /** Error code identifying the type of error */
    code: string;
}
