// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../../../environments.js";
import * as errors from "../../../../../../../../../../../../errors/index.js";
import * as Deepgram from "../../../../../../../../../../../index.js";

export declare namespace BreakdownClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BreakdownClient {
    protected readonly _options: BreakdownClient.Options;

    constructor(options: BreakdownClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Retrieves the billing summary for a specific project, with various filter options or by grouping options.
     *
     * @param {string} project_id - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.billing.BreakdownListRequest} request
     * @param {BreakdownClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.billing.breakdown.list("123456-7890-1234-5678-901234", {
     *         start: "start",
     *         end: "end",
     *         accessor: "12345678-1234-1234-1234-123456789012",
     *         deployment: "hosted",
     *         tag: "tag1",
     *         line_item: "streaming::nova-3"
     *     })
     */
    public list(
        project_id: string,
        request: Deepgram.manage.v1.projects.billing.BreakdownListRequest = {},
        requestOptions?: BreakdownClient.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.BillingBreakdownV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(project_id, request, requestOptions));
    }

    private async __list(
        project_id: string,
        request: Deepgram.manage.v1.projects.billing.BreakdownListRequest = {},
        requestOptions?: BreakdownClient.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.BillingBreakdownV1Response>> {
        const { start, end, accessor, deployment, tag, line_item: lineItem, grouping } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (start != null) {
            _queryParams.start = start;
        }

        if (end != null) {
            _queryParams.end = end;
        }

        if (accessor != null) {
            _queryParams.accessor = accessor;
        }

        if (deployment != null) {
            _queryParams.deployment = deployment;
        }

        if (tag != null) {
            _queryParams.tag = tag;
        }

        if (lineItem != null) {
            _queryParams.line_item = lineItem;
        }

        if (grouping != null) {
            if (Array.isArray(grouping)) {
                _queryParams.grouping = grouping.map((item) => item);
            } else {
                _queryParams.grouping = grouping;
            }
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${core.url.encodePathParam(project_id)}/billing/breakdown`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.BillingBreakdownV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling GET /v1/projects/{project_id}/billing/breakdown.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env.DEEPGRAM_API_KEY;
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
