/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../../../../../environments.js";
import * as core from "../../../../../../../../../../../../core/index.js";
import * as Deepgram from "../../../../../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../../../../../errors/index.js";

export declare namespace Breakdown {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Breakdown {
    protected readonly _options: Breakdown.Options;

    constructor(_options: Breakdown.Options = {}) {
        this._options = _options;
    }

    /**
     * Retrieves the billing summary for a specific project, with various filter options or by grouping options.
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.billing.BreakdownListRequest} request
     * @param {Breakdown.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.billing.breakdown.list("123456-7890-1234-5678-901234", {
     *         start: "start",
     *         end: "end",
     *         accessor: "12345678-1234-1234-1234-123456789012",
     *         deployment: "hosted",
     *         tag: "tag1",
     *         line_item: "streaming::nova-3"
     *     })
     */
    public list(
        projectId: string,
        request: Deepgram.manage.v1.projects.billing.BreakdownListRequest = {},
        requestOptions?: Breakdown.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.BillingBreakdownV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(projectId, request, requestOptions));
    }

    private async __list(
        projectId: string,
        request: Deepgram.manage.v1.projects.billing.BreakdownListRequest = {},
        requestOptions?: Breakdown.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.BillingBreakdownV1Response>> {
        const { start, end, accessor, deployment, tag, line_item: lineItem, grouping } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (start != null) {
            _queryParams["start"] = start;
        }

        if (end != null) {
            _queryParams["end"] = end;
        }

        if (accessor != null) {
            _queryParams["accessor"] = accessor;
        }

        if (deployment != null) {
            _queryParams["deployment"] = deployment;
        }

        if (tag != null) {
            _queryParams["tag"] = tag;
        }

        if (lineItem != null) {
            _queryParams["line_item"] = lineItem;
        }

        if (grouping != null) {
            if (Array.isArray(grouping)) {
                _queryParams["grouping"] = grouping.map((item) => item);
            } else {
                _queryParams["grouping"] = grouping;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}/billing/breakdown`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.BillingBreakdownV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling GET /v1/projects/{project_id}/billing/breakdown.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
