/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import { Think } from "../resources/think/client/Client.js";

export declare namespace Settings {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class Settings {
    protected readonly _options: Settings.Options;
    protected _think: Think | undefined;

    constructor(_options: Settings.Options = {}) {
        this._options = _options;
    }

    public get think(): Think {
        return (this._think ??= new Think(this._options));
    }
}
