// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../../../BaseClient.js";
import { ThinkClient } from "../resources/think/client/Client.js";

export declare namespace SettingsClient {
    export interface Options extends BaseClientOptions {}
}

export class SettingsClient {
    protected readonly _options: SettingsClient.Options;
    protected _think: ThinkClient | undefined;

    constructor(options: SettingsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get think(): ThinkClient {
        return (this._think ??= new ThinkClient(this._options));
    }
}
