// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { TextClient } from "../resources/text/client/Client.js";

export declare namespace V1Client {
    export interface Options extends BaseClientOptions {}
}

export class V1Client {
    protected readonly _options: NormalizedClientOptionsWithAuth<V1Client.Options>;
    protected _text: TextClient | undefined;

    constructor(options: V1Client.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get text(): TextClient {
        return (this._text ??= new TextClient(this._options));
    }
}
