// This file was auto-generated by Fern from our API Definition.

/** Deployment type for the requests */
export const BreakdownListRequestDeployment = {
    Hosted: "hosted",
    Beta: "beta",
    SelfHosted: "self-hosted",
} as const;
export type BreakdownListRequestDeployment =
    (typeof BreakdownListRequestDeployment)[keyof typeof BreakdownListRequestDeployment];
