// This file was auto-generated by Fern from our API Definition.

export const BreakdownListRequestGroupingItem = {
    Accessor: "accessor",
    Deployment: "deployment",
    LineItem: "line_item",
    Tags: "tags",
} as const;
export type BreakdownListRequestGroupingItem =
    (typeof BreakdownListRequestGroupingItem)[keyof typeof BreakdownListRequestGroupingItem];
