// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../src/api/index";
import { DeepgramClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("DistributionCredentialsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            distribution_credentials: [
                {
                    member: { member_id: "3376abcd-8e5e-49d3-92d4-876d3a4f0363", email: "email@example.com" },
                    distribution_credentials: {
                        distribution_credentials_id: "8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
                        provider: "quay",
                        comment: "My Self-Hosted Distribution Credentials",
                        scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                        created: "2023-06-28T15:36:59Z",
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/self-hosted/distribution/credentials")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.selfHosted.v1.distributionCredentials.list("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            distribution_credentials: [
                {
                    member: {
                        member_id: "3376abcd-8e5e-49d3-92d4-876d3a4f0363",
                        email: "email@example.com",
                    },
                    distribution_credentials: {
                        distribution_credentials_id: "8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
                        provider: "quay",
                        comment: "My Self-Hosted Distribution Credentials",
                        scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                        created: "2023-06-28T15:36:59Z",
                    },
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/self-hosted/distribution/credentials")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.selfHosted.v1.distributionCredentials.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            member: { member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83", email: "email@example.com" },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/projects/123456-7890-1234-5678-901234/self-hosted/distribution/credentials")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.selfHosted.v1.distributionCredentials.create("123456-7890-1234-5678-901234", {
            provider: "quay",
        });
        expect(response).toEqual({
            member: {
                member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83",
                email: "email@example.com",
            },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/self-hosted/distribution/credentials")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.selfHosted.v1.distributionCredentials.create("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            member: { member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83", email: "email@example.com" },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        };
        server
            .mockEndpoint()
            .get(
                "/v1/projects/123456-7890-1234-5678-901234/self-hosted/distribution/credentials/8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.selfHosted.v1.distributionCredentials.get(
            "123456-7890-1234-5678-901234",
            "8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
        );
        expect(response).toEqual({
            member: {
                member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83",
                email: "email@example.com",
            },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/self-hosted/distribution/credentials/distribution_credentials_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.selfHosted.v1.distributionCredentials.get("project_id", "distribution_credentials_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            member: { member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83", email: "email@example.com" },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        };
        server
            .mockEndpoint()
            .delete(
                "/v1/projects/123456-7890-1234-5678-901234/self-hosted/distribution/credentials/8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.selfHosted.v1.distributionCredentials.delete(
            "123456-7890-1234-5678-901234",
            "8b36cfd0-472f-4a21-833f-2d6343c3a2f3",
        );
        expect(response).toEqual({
            member: {
                member_id: "c7b9b131-73f3-11d9-8665-0b00d2e44b83",
                email: "email@example.com",
            },
            distribution_credentials: {
                distribution_credentials_id: "82c32c10-53b2-4d23-993f-864b3d44502a",
                provider: "quay",
                comment: "My Self-Hosted Distribution Credentials",
                scopes: ["self-hosted:product:api", "self-hosted:product:engine"],
                created: "2023-06-28T15:36:59Z",
            },
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/projects/project_id/self-hosted/distribution/credentials/distribution_credentials_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.selfHosted.v1.distributionCredentials.delete(
                "project_id",
                "distribution_credentials_id",
            );
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
