// This file was auto-generated by Fern from our API Definition.

export interface SpeakV2Speak {
    /** Message type identifier */
    type: "Speak";
    /** The input text to synthesize. May contain inline pronunciation controls (`\{"word": "...", "pronounce": "<IPA>"\}`), which are in Early Access. Inline pause controls are supported on the batch (REST) transport only; a pause marker sent over the WebSocket fails the connection with `DATA-0002`. Pronunciation cannot be combined with a `speed` other than `1.0`: text carrying a pronunciation control on a session opened with `speed`, or after a `Configure` that set it, also fails the connection with `DATA-0002`. See the SDK-local Flux TTS Controls guide in `docs/FluxTtsControls.md`. */
    text: string;
}
