// This file was auto-generated by Fern from our API Definition.

export interface SpeakV2Connected {
    /** Message type identifier */
    type: "Connected";
    /** The unique identifier of the `/v2/speak` request */
    request_id: string;
    /** Resolved model name */
    model_name: string;
    /** Resolved model version */
    model_version: string;
    /** Resolved model UUIDs. A list, because a resolved model may be backed by more than one underlying model. */
    model_uuids: string[];
}
