// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface SpeakV2Configure {
    /** Message type identifier */
    type: "Configure";
    speed?: Deepgram.SpeakV2SpeedValue | undefined;
}
