// This file was auto-generated by Fern from our API Definition.

export interface SpeakV2Speak {
    /** Message type identifier */
    type: "Speak";
    /** The input text to synthesize. Inline pause and pronunciation controls are not yet applied; they are stripped from the text before synthesis. */
    text: string;
}
