// This file was auto-generated by Fern from our API Definition.

export interface SpeakV2SpeechMetadata {
    /** Message type identifier */
    type: "SpeechMetadata";
    /** Server-assigned turn identifier */
    speech_id: string;
    /** Total audio duration produced for this turn, in milliseconds */
    audio_duration_ms: number;
    /** Raw input character count for this turn, before text normalization */
    input_character_count: number;
    /** Billable character count for this turn — the input character count with stripped control characters removed. Always less than or equal to `input_character_count`. */
    billable_character_count: number;
    /** Controls applied during the turn. Inline pronunciation and pause controls are not available during Early Access, so every count is currently `0`. */
    controls_applied: SpeakV2SpeechMetadata.ControlsApplied;
}

export namespace SpeakV2SpeechMetadata {
    /**
     * Controls applied during the turn. Inline pronunciation and pause controls are not available during Early Access, so every count is currently `0`.
     */
    export interface ControlsApplied {
        /** Pronunciation overrides successfully applied. Mirrors the Aura-2 `dg-pronunciations-applied` REST header. Always `0` during Early Access. */
        pronunciations_applied: number;
        /** Pronunciation entries that triggered a warning (invalid IPA, word too long). Mirrors the Aura-2 `dg-pronunciation-warnings` REST header. Always `0` during Early Access. */
        pronunciation_warnings: number;
    }
}
