// This file was auto-generated by Fern from our API Definition.

export interface SpeakV2SpeechMetadata {
    /** Message type identifier */
    type: "SpeechMetadata";
    /** Server-assigned turn identifier */
    speech_id: string;
    /** Total audio duration produced for this turn, in milliseconds */
    audio_duration_ms: number;
    /** Raw input character count for this turn, before text normalization */
    input_character_count: number;
    /** Billable character count for this turn — the input character count with stripped control characters removed. Always less than or equal to `input_character_count`. */
    billable_character_count: number;
    /** Counts of the inline controls the server acted on during the turn. A pronunciation override that triggers an IPA warning is still applied best-effort and counted in `pronunciations_applied`; the warning is reported separately through a `Warning` and `pronunciation_warnings`. */
    controls_applied: SpeakV2SpeechMetadata.ControlsApplied;
}

export namespace SpeakV2SpeechMetadata {
    /**
     * Counts of the inline controls the server acted on during the turn. A pronunciation override that triggers an IPA warning is still applied best-effort and counted in `pronunciations_applied`; the warning is reported separately through a `Warning` and `pronunciation_warnings`.
     */
    export interface ControlsApplied {
        /** Pronunciation overrides successfully applied. Mirrors the Aura-2 `dg-pronunciations-applied` REST header. */
        pronunciations_applied: number;
        /** Pause (break) controls successfully applied. Mirrors the Aura-2 `dg-breaks-applied` REST header. Always `0` on the WebSocket, where inline pause controls are not supported. */
        breaks_applied: number;
        /** Pronunciation entries that triggered a warning (invalid IPA, word too long). On batch requests the corresponding `PRON-NNN` codes are returned in the `dg-warnings` response header. */
        pronunciation_warnings: number;
    }
}
