// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../src/api/index";
import { DeepgramClient } from "../../../../src/index";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { projects: [{ project_id: "project_id", name: "name" }] };
        server.mockEndpoint().get("/v1/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.manage.v1.projects.list();
        expect(response).toEqual({
            projects: [
                {
                    project_id: "project_id",
                    name: "name",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/projects").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.manage.v1.projects.list();
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { project_id: "project_id", mip_opt_out: true, name: "name" };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.get("123456-7890-1234-5678-901234", {
            limit: 1.1,
            page: 1.1,
        });
        expect(response).toEqual({
            project_id: "project_id",
            mip_opt_out: true,
            name: "name",
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.get("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/v1/projects/123456-7890-1234-5678-901234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.delete("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            message: "message",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/projects/project_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.delete("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "Successfully updated project info." };
        server
            .mockEndpoint()
            .patch("/v1/projects/123456-7890-1234-5678-901234")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.update("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            message: "Successfully updated project info.",
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/projects/project_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.update("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("leave (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/v1/projects/123456-7890-1234-5678-901234/leave")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.leave("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            message: "message",
        });
    });

    test("leave (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/projects/project_id/leave")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.leave("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
