// This file was auto-generated by Fern from our API Definition.

/** Deployment type for the requests */
export const BreakdownGetRequestDeployment = {
    Hosted: "hosted",
    Beta: "beta",
    SelfHosted: "self-hosted",
} as const;
export type BreakdownGetRequestDeployment =
    | (typeof BreakdownGetRequestDeployment)[keyof typeof BreakdownGetRequestDeployment]
    | string;
