/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Method type for the request
 */
export type BreakdownGetRequestMethod = "sync" | "async" | "streaming";
export const BreakdownGetRequestMethod = {
    Sync: "sync",
    Async: "async",
    Streaming: "streaming",
} as const;
