/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BreakdownGetRequestEndpoint = "listen" | "read" | "speak" | "agent";
export const BreakdownGetRequestEndpoint = {
    Listen: "listen",
    Read: "read",
    Speak: "speak",
    Agent: "agent",
} as const;
