/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BreakdownGetRequestGrouping =
    | "accessor"
    | "endpoint"
    | "feature_set"
    | "models"
    | "method"
    | "tags"
    | "deployment";
export const BreakdownGetRequestGrouping = {
    Accessor: "accessor",
    Endpoint: "endpoint",
    FeatureSet: "feature_set",
    Models: "models",
    Method: "method",
    Tags: "tags",
    Deployment: "deployment",
} as const;
