// This file was auto-generated by Fern from our API Definition.

export const BreakdownGetRequestEndpoint = {
    Listen: "listen",
    Read: "read",
    Speak: "speak",
    Agent: "agent",
} as const;
export type BreakdownGetRequestEndpoint =
    | (typeof BreakdownGetRequestEndpoint)[keyof typeof BreakdownGetRequestEndpoint]
    | string;
