/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Deployment type for the requests
 */
export type BreakdownGetRequestDeployment = "hosted" | "beta" | "self-hosted";
export const BreakdownGetRequestDeployment = {
    Hosted: "hosted",
    Beta: "beta",
    SelfHosted: "self-hosted",
} as const;
