---
extends: relaxed

rules:
  line-length: disable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  indentation: disable
  key-duplicates: disable
  empty-lines: enable
  colons: disable
  commas: disable

ignore: |
  /deepgram-js-sdk/node_modules/**/*/
