/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         include_outdated: true
 *     }
 */
export interface ModelsListRequest {
    /** returns non-latest versions of models */
    include_outdated?: boolean;
}
