// This file was auto-generated by Fern from our API Definition.

import * as core from "../../../../../../core/index.js";
import { fromJson, toJson } from "../../../../../../core/json.js";
import type * as Deepgram from "../../../../../index.js";

export declare namespace V1Socket {
    export interface Args {
        socket: core.ReconnectingWebSocket;
    }

    export type Response =
        | Deepgram.agent.AgentV1ListenUpdated
        | Deepgram.agent.AgentV1ThinkUpdated
        | Deepgram.agent.AgentV1ReceiveFunctionCallResponse
        | Deepgram.agent.AgentV1PromptUpdated
        | Deepgram.agent.AgentV1SpeakUpdated
        | Deepgram.agent.AgentV1InjectionRefused
        | Deepgram.agent.AgentV1Welcome
        | Deepgram.agent.AgentV1SettingsApplied
        | Deepgram.agent.AgentV1ConversationText
        | Deepgram.agent.AgentV1UserStartedSpeaking
        | Deepgram.agent.AgentV1AgentThinking
        | Deepgram.agent.AgentV1LatencyReport
        | Deepgram.agent.AgentV1FunctionCallRequest
        | Deepgram.agent.AgentV1FunctionCallCancelled
        | Deepgram.agent.AgentV1AgentStartedSpeaking
        | Deepgram.agent.AgentV1AgentAudioDone
        | Deepgram.agent.AgentV1Error
        | Deepgram.agent.AgentV1Warning
        | Deepgram.agent.AgentV1History
        | string;
    type EventHandlers = {
        open?: () => void;
        message?: (message: Response) => void;
        close?: (event: core.CloseEvent) => void;
        error?: (error: Error) => void;
    };
}

export class V1Socket {
    public readonly socket: core.ReconnectingWebSocket;
    protected readonly eventHandlers: {
        [K in keyof V1Socket.EventHandlers]-?: Array<NonNullable<V1Socket.EventHandlers[K]>>;
    } = { open: [], message: [], close: [], error: [] };
    private handleOpen: () => void = () => {
        for (const handler of [...this.eventHandlers.open]) {
            handler();
        }
    };
    private handleMessage: (event: { data: string }) => void = (event) => {
        const data = fromJson(event.data);

        for (const handler of [...this.eventHandlers.message]) {
            handler(data as V1Socket.Response);
        }
    };
    private handleClose: (event: core.CloseEvent) => void = (event) => {
        for (const handler of [...this.eventHandlers.close]) {
            handler(event);
        }
    };
    private handleError: (event: core.ErrorEvent) => void = (event) => {
        const message = event.message;
        for (const handler of [...this.eventHandlers.error]) {
            handler(new Error(message));
        }
    };

    constructor(args: V1Socket.Args) {
        this.socket = args.socket;
        this.socket.addEventListener("open", this.handleOpen);
        this.socket.addEventListener("message", this.handleMessage);
        this.socket.addEventListener("close", this.handleClose);
        this.socket.addEventListener("error", this.handleError);
    }

    /** The current state of the connection; this is one of the readyState constants. */
    get readyState(): core.ReconnectingWebSocket.ReadyState {
        return this.socket.readyState;
    }

    /**
     * @param event - The event to attach to.
     * @param callback - The callback to run when the event is triggered.
     * Usage:
     * ```typescript
     * this.on('open', () => {
     *     console.log('The websocket is open');
     * });
     * ```
     */
    public on<T extends keyof V1Socket.EventHandlers>(event: T, callback: V1Socket.EventHandlers[T]): void {
        const handlers = this.eventHandlers[event] as Array<NonNullable<V1Socket.EventHandlers[T]>>;
        if (callback == null) {
            handlers.length = 0;
        } else {
            handlers.splice(0, handlers.length, callback);
        }
    }

    /**
     * @param event - The event to detach from.
     * @param callback - The callback previously registered with `on`. No-op if it is not registered for this event.
     * Usage:
     * ```typescript
     * const handler = () => console.log('The websocket is open');
     * this.on('open', handler);
     * this.off('open', handler);
     * ```
     */
    public off<T extends keyof V1Socket.EventHandlers>(
        event: T,
        callback: NonNullable<V1Socket.EventHandlers[T]>,
    ): void {
        const handlers = this.eventHandlers[event] as Array<NonNullable<V1Socket.EventHandlers[T]>>;
        const index = handlers.lastIndexOf(callback);
        if (index !== -1) {
            handlers.splice(index, 1);
        }
    }

    public sendSettings(message: Deepgram.agent.AgentV1Settings): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendUpdateListen(message: Deepgram.agent.AgentV1UpdateListen): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendUpdateThink(message: Deepgram.agent.AgentV1UpdateThink): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendUpdateSpeak(message: Deepgram.agent.AgentV1UpdateSpeak): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendInjectUserMessage(message: Deepgram.agent.AgentV1InjectUserMessage): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendInjectAgentMessage(message: Deepgram.agent.AgentV1InjectAgentMessage): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendFunctionCallResponse(message: Deepgram.agent.AgentV1SendFunctionCallResponse): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendKeepAlive(message: Deepgram.agent.AgentV1KeepAlive): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendUpdatePrompt(message: Deepgram.agent.AgentV1UpdatePrompt): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendForceEndTurn(message: Deepgram.agent.AgentV1ForceEndTurn): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendMedia(message: ArrayBuffer | Blob | ArrayBufferView): void {
        this.assertSocketIsOpen();
        this.sendBinary(message);
    }

    /** Connect to the websocket and register event handlers. */
    public connect(): V1Socket {
        this.socket.reconnect();

        this.socket.addEventListener("open", this.handleOpen);
        this.socket.addEventListener("message", this.handleMessage);
        this.socket.addEventListener("close", this.handleClose);
        this.socket.addEventListener("error", this.handleError);

        return this;
    }

    /** Close the websocket and unregister event handlers. */
    public close(): void {
        this.socket.close();

        this.handleClose({ code: 1000 } as CloseEvent);

        this.socket.removeEventListener("open", this.handleOpen);
        this.socket.removeEventListener("message", this.handleMessage);
        this.socket.removeEventListener("close", this.handleClose);
        this.socket.removeEventListener("error", this.handleError);
    }

    /** Returns a promise that resolves when the websocket is open. */
    public async waitForOpen(): Promise<core.ReconnectingWebSocket> {
        if (this.socket.readyState === core.ReconnectingWebSocket.ReadyState.OPEN) {
            return this.socket;
        }

        return new Promise((resolve, reject) => {
            this.socket.addEventListener("open", () => {
                resolve(this.socket);
            });

            this.socket.addEventListener("error", (event: unknown) => {
                reject(event);
            });
        });
    }

    /** Asserts that the websocket is open. */
    private assertSocketIsOpen(): void {
        if (!this.socket) {
            throw new Error("Socket is not connected.");
        }

        if (this.socket.readyState !== core.ReconnectingWebSocket.ReadyState.OPEN) {
            throw new Error("Socket is not open.");
        }
    }

    /** Send a binary payload to the websocket. */
    protected sendBinary(payload: ArrayBuffer | Blob | ArrayBufferView): void {
        this.socket.send(payload);
    }

    /** Send a JSON payload to the websocket. */
    protected sendJson(
        payload:
            | Deepgram.agent.AgentV1Settings
            | Deepgram.agent.AgentV1UpdateListen
            | Deepgram.agent.AgentV1UpdateThink
            | Deepgram.agent.AgentV1UpdateSpeak
            | Deepgram.agent.AgentV1InjectUserMessage
            | Deepgram.agent.AgentV1InjectAgentMessage
            | Deepgram.agent.AgentV1SendFunctionCallResponse
            | Deepgram.agent.AgentV1KeepAlive
            | Deepgram.agent.AgentV1UpdatePrompt
            | Deepgram.agent.AgentV1ForceEndTurn
            | string,
    ): void {
        const jsonPayload = toJson(payload);
        this.socket.send(jsonPayload);
    }
}
