/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../../core/index.js";
import * as Deepgram from "../../../../../index.js";
import { fromJson, toJson } from "../../../../../../core/json.js";

export declare namespace V1Socket {
    export interface Args {
        socket: core.ReconnectingWebSocket;
    }

    export type Response =
        | Deepgram.agent.AgentV1ReceiveFunctionCallResponse
        | Deepgram.agent.AgentV1PromptUpdated
        | Deepgram.agent.AgentV1SpeakUpdated
        | Deepgram.agent.AgentV1InjectionRefused
        | Deepgram.agent.AgentV1Welcome
        | Deepgram.agent.AgentV1SettingsApplied
        | Deepgram.agent.AgentV1ConversationText
        | Deepgram.agent.AgentV1UserStartedSpeaking
        | Deepgram.agent.AgentV1AgentThinking
        | Deepgram.agent.AgentV1FunctionCallRequest
        | Deepgram.agent.AgentV1AgentStartedSpeaking
        | Deepgram.agent.AgentV1AgentAudioDone
        | Deepgram.agent.AgentV1Error
        | Deepgram.agent.AgentV1Warning
        | string;
    type EventHandlers = {
        open?: () => void;
        message?: (message: Response) => void;
        close?: (event: core.CloseEvent) => void;
        error?: (error: Error) => void;
    };
}

export class V1Socket {
    public readonly socket: core.ReconnectingWebSocket;
    protected readonly eventHandlers: V1Socket.EventHandlers = {};
    private handleOpen: () => void = () => {
        this.eventHandlers.open?.();
    };
    private handleMessage: (event: { data: string }) => void = (event) => {
        const data = fromJson(event.data);

        this.eventHandlers.message?.(data as V1Socket.Response);
    };
    private handleClose: (event: core.CloseEvent) => void = (event) => {
        this.eventHandlers.close?.(event);
    };
    private handleError: (event: core.ErrorEvent) => void = (event) => {
        const message = event.message;
        this.eventHandlers.error?.(new Error(message));
    };

    constructor(args: V1Socket.Args) {
        this.socket = args.socket;
        this.socket.addEventListener("open", this.handleOpen);
        this.socket.addEventListener("message", this.handleMessage);
        this.socket.addEventListener("close", this.handleClose);
        this.socket.addEventListener("error", this.handleError);
    }

    /** The current state of the connection; this is one of the readyState constants. */
    get readyState(): number {
        return this.socket.readyState;
    }

    /**
     * @param event - The event to attach to.
     * @param callback - The callback to run when the event is triggered.
     * Usage:
     * ```typescript
     * this.on('open', () => {
     *     console.log('The websocket is open');
     * });
     * ```
     */
    public on<T extends keyof V1Socket.EventHandlers>(event: T, callback: V1Socket.EventHandlers[T]) {
        this.eventHandlers[event] = callback;
    }

    public sendAgentV1Settings(message: Deepgram.agent.AgentV1Settings): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1UpdateSpeak(message: Deepgram.agent.AgentV1UpdateSpeak): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1InjectUserMessage(message: Deepgram.agent.AgentV1InjectUserMessage): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1InjectAgentMessage(message: Deepgram.agent.AgentV1InjectAgentMessage): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1SendFunctionCallResponse(message: Deepgram.agent.AgentV1SendFunctionCallResponse): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1KeepAlive(message: Deepgram.agent.AgentV1KeepAlive): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1UpdatePrompt(message: Deepgram.agent.AgentV1UpdatePrompt): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    public sendAgentV1Media(message: string): void {
        this.assertSocketIsOpen();
        this.sendJson(message);
    }

    /** Connect to the websocket and register event handlers. */
    public connect(): V1Socket {
        this.socket.reconnect();

        this.socket.addEventListener("open", this.handleOpen);
        this.socket.addEventListener("message", this.handleMessage);
        this.socket.addEventListener("close", this.handleClose);
        this.socket.addEventListener("error", this.handleError);

        return this;
    }

    /** Close the websocket and unregister event handlers. */
    public close(): void {
        this.socket.close();

        this.handleClose({ code: 1000 } as CloseEvent);

        this.socket.removeEventListener("open", this.handleOpen);
        this.socket.removeEventListener("message", this.handleMessage);
        this.socket.removeEventListener("close", this.handleClose);
        this.socket.removeEventListener("error", this.handleError);
    }

    /** Returns a promise that resolves when the websocket is open. */
    public async waitForOpen(): Promise<core.ReconnectingWebSocket> {
        if (this.socket.readyState === core.ReconnectingWebSocket.OPEN) {
            return this.socket;
        }

        return new Promise((resolve, reject) => {
            this.socket.addEventListener("open", () => {
                resolve(this.socket);
            });

            this.socket.addEventListener("error", (event: unknown) => {
                reject(event);
            });
        });
    }

    /** Asserts that the websocket is open. */
    private assertSocketIsOpen(): void {
        if (!this.socket) {
            throw new Error("Socket is not connected.");
        }

        if (this.socket.readyState !== core.ReconnectingWebSocket.OPEN) {
            throw new Error("Socket is not open.");
        }
    }

    /** Send a binary payload to the websocket. */
    protected sendBinary(payload: ArrayBufferLike | Blob | ArrayBufferView): void {
        this.socket.send(payload);
    }

    /** Send a JSON payload to the websocket. */
    protected sendJson(
        payload:
            | Deepgram.agent.AgentV1Settings
            | Deepgram.agent.AgentV1UpdateSpeak
            | Deepgram.agent.AgentV1InjectUserMessage
            | Deepgram.agent.AgentV1InjectAgentMessage
            | Deepgram.agent.AgentV1SendFunctionCallResponse
            | Deepgram.agent.AgentV1KeepAlive
            | Deepgram.agent.AgentV1UpdatePrompt
            | string,
    ): void {
        const jsonPayload = toJson(payload);
        this.socket.send(jsonPayload);
    }
}
