// This file was auto-generated by Fern from our API Definition.

export const MediaTranscribeRequestCustomIntentMode = {
    Extended: "extended",
    Strict: "strict",
} as const;
export type MediaTranscribeRequestCustomIntentMode =
    | (typeof MediaTranscribeRequestCustomIntentMode)[keyof typeof MediaTranscribeRequestCustomIntentMode]
    | string;
