// This file was auto-generated by Fern from our API Definition.

export const MediaTranscribeRequestDiarizeModel = {
    Latest: "latest",
    V1: "v1",
    V2: "v2",
} as const;
export type MediaTranscribeRequestDiarizeModel =
    | (typeof MediaTranscribeRequestDiarizeModel)[keyof typeof MediaTranscribeRequestDiarizeModel]
    | string;
