// This file was auto-generated by Fern from our API Definition.

export const MediaTranscribeRequestCustomTopicMode = {
    Extended: "extended",
    Strict: "strict",
} as const;
export type MediaTranscribeRequestCustomTopicMode =
    | (typeof MediaTranscribeRequestCustomTopicMode)[keyof typeof MediaTranscribeRequestCustomTopicMode]
    | string;
