/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaTranscribeRequestCustomIntentMode = "extended" | "strict";
export const MediaTranscribeRequestCustomIntentMode = {
    Extended: "extended",
    Strict: "strict",
} as const;
