/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaTranscribeRequestEncoding =
    | "linear16"
    | "flac"
    | "mulaw"
    | "amr-nb"
    | "amr-wb"
    | "opus"
    | "speex"
    | "g729";
export const MediaTranscribeRequestEncoding = {
    Linear16: "linear16",
    Flac: "flac",
    Mulaw: "mulaw",
    AmrNb: "amr-nb",
    AmrWb: "amr-wb",
    Opus: "opus",
    Speex: "speex",
    G729: "g729",
} as const;
