/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Deepgram from "../../../../../../../index.js";

export type MediaTranscribeResponse = Deepgram.ListenV1Response | Deepgram.ListenV1AcceptedResponse;
