/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaTranscribeRequestModel =
    | "nova-3"
    | "nova-3-general"
    | "nova-3-medical"
    | "nova-2"
    | "nova-2-general"
    | "nova-2-meeting"
    | "nova-2-finance"
    | "nova-2-conversationalai"
    | "nova-2-voicemail"
    | "nova-2-video"
    | "nova-2-medical"
    | "nova-2-drivethru"
    | "nova-2-automotive"
    | "nova"
    | "nova-general"
    | "nova-phonecall"
    | "nova-medical"
    | "enhanced"
    | "enhanced-general"
    | "enhanced-meeting"
    | "enhanced-phonecall"
    | "enhanced-finance"
    | "base"
    | "meeting"
    | "phonecall"
    | "finance"
    | "conversationalai"
    | "voicemail"
    | "video";
export const MediaTranscribeRequestModel = {
    Nova3: "nova-3",
    Nova3General: "nova-3-general",
    Nova3Medical: "nova-3-medical",
    Nova2: "nova-2",
    Nova2General: "nova-2-general",
    Nova2Meeting: "nova-2-meeting",
    Nova2Finance: "nova-2-finance",
    Nova2Conversationalai: "nova-2-conversationalai",
    Nova2Voicemail: "nova-2-voicemail",
    Nova2Video: "nova-2-video",
    Nova2Medical: "nova-2-medical",
    Nova2Drivethru: "nova-2-drivethru",
    Nova2Automotive: "nova-2-automotive",
    Nova: "nova",
    NovaGeneral: "nova-general",
    NovaPhonecall: "nova-phonecall",
    NovaMedical: "nova-medical",
    Enhanced: "enhanced",
    EnhancedGeneral: "enhanced-general",
    EnhancedMeeting: "enhanced-meeting",
    EnhancedPhonecall: "enhanced-phonecall",
    EnhancedFinance: "enhanced-finance",
    Base: "base",
    Meeting: "meeting",
    Phonecall: "phonecall",
    Finance: "finance",
    Conversationalai: "conversationalai",
    Voicemail: "voicemail",
    Video: "video",
} as const;
