/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MediaTranscribeRequestVersion = "latest";
export const MediaTranscribeRequestVersion = {
    Latest: "latest",
} as const;
