// This file was auto-generated by Fern from our API Definition.

// Backward-compat patch (2026-08-19 regen): the generator re-parented this class from
// `Error` to `DeepgramError`. That is arguably the better hierarchy — a timeout IS a
// Deepgram error, and today it is the one error type the SDK's own base class fails to
// catch — but it is a silent breaking change for existing callers. Any ordered catch of
// the form
//
//     if (e instanceof DeepgramError) { ... } else if (e instanceof DeepgramTimeoutError) { ... }
//
// quietly stops reaching the timeout branch, and the timeout instead surfaces as an API
// error whose `statusCode` is undefined. Nothing fails at compile time, so the change
// would land in user code unnoticed. Reverted to `extends Error` to keep this regen
// non-breaking; adopt the new hierarchy in a deliberate major where it can be documented.
export class DeepgramTimeoutError extends Error {
    public readonly cause?: unknown;

    constructor(message: string, opts?: { cause?: unknown }) {
        super(message);
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "DeepgramTimeoutError";
        if (opts?.cause != null) {
            this.cause = opts.cause;
        }
    }
}
