// This file was auto-generated by Fern from our API Definition.

export const TextAnalyzeRequestCallbackMethod = {
    Post: "POST",
    Put: "PUT",
} as const;
export type TextAnalyzeRequestCallbackMethod =
    | (typeof TextAnalyzeRequestCallbackMethod)[keyof typeof TextAnalyzeRequestCallbackMethod]
    | string;
