/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TextAnalyzeRequestCustomTopicMode = "extended" | "strict";
export const TextAnalyzeRequestCustomTopicMode = {
    Extended: "extended",
    Strict: "strict",
} as const;
