/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TextAnalyzeRequestCallbackMethod = "POST" | "PUT";
export const TextAnalyzeRequestCallbackMethod = {
    Post: "POST",
    Put: "PUT",
} as const;
