// This file was auto-generated by Fern from our API Definition.

export const TextAnalyzeRequestSummarize = {
    V2: "v2",
} as const;
export type TextAnalyzeRequestSummarize =
    (typeof TextAnalyzeRequestSummarize)[keyof typeof TextAnalyzeRequestSummarize];
