// This file was auto-generated by Fern from our API Definition.

export const TextAnalyzeRequestCustomTopicMode = {
    Extended: "extended",
    Strict: "strict",
} as const;
export type TextAnalyzeRequestCustomTopicMode =
    (typeof TextAnalyzeRequestCustomTopicMode)[keyof typeof TextAnalyzeRequestCustomTopicMode];
