/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as Deepgram from "../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../errors/index.js";

export declare namespace Media {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Media {
    protected readonly _options: Media.Options;

    constructor(_options: Media.Options = {}) {
        this._options = _options;
    }

    /**
     * Transcribe audio and video using Deepgram's speech-to-text REST API
     *
     * @param {Deepgram.listen.v1.ListenV1RequestUrl} request
     * @param {Media.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.listen.v1.media.transcribeUrl({
     *         callback: "callback",
     *         callback_method: "POST",
     *         extra: "extra",
     *         sentiment: true,
     *         summarize: "v2",
     *         tag: "tag",
     *         topics: true,
     *         custom_topic: "custom_topic",
     *         custom_topic_mode: "extended",
     *         intents: true,
     *         custom_intent: "custom_intent",
     *         custom_intent_mode: "extended",
     *         detect_entities: true,
     *         detect_language: true,
     *         diarize: true,
     *         dictation: true,
     *         encoding: "linear16",
     *         filler_words: true,
     *         keywords: "keywords",
     *         language: "language",
     *         measurements: true,
     *         model: "nova-3",
     *         multichannel: true,
     *         numerals: true,
     *         paragraphs: true,
     *         profanity_filter: true,
     *         punctuate: true,
     *         redact: "redact",
     *         replace: "replace",
     *         search: "search",
     *         smart_format: true,
     *         utterances: true,
     *         utt_split: 1.1,
     *         version: "latest",
     *         mip_opt_out: true,
     *         url: "https://dpgr.am/spacewalk.wav"
     *     })
     */
    public transcribeUrl(
        request: Deepgram.listen.v1.ListenV1RequestUrl,
        requestOptions?: Media.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.listen.v1.MediaTranscribeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__transcribeUrl(request, requestOptions));
    }

    private async __transcribeUrl(
        request: Deepgram.listen.v1.ListenV1RequestUrl,
        requestOptions?: Media.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.listen.v1.MediaTranscribeResponse>> {
        const {
            callback,
            callback_method: callbackMethod,
            extra,
            sentiment,
            summarize,
            tag,
            topics,
            custom_topic: customTopic,
            custom_topic_mode: customTopicMode,
            intents,
            custom_intent: customIntent,
            custom_intent_mode: customIntentMode,
            detect_entities: detectEntities,
            detect_language: detectLanguage,
            diarize,
            dictation,
            encoding,
            filler_words: fillerWords,
            keyterm,
            keywords,
            language,
            measurements,
            model,
            multichannel,
            numerals,
            paragraphs,
            profanity_filter: profanityFilter,
            punctuate,
            redact,
            replace,
            search,
            smart_format: smartFormat,
            utterances,
            utt_split: uttSplit,
            version,
            mip_opt_out: mipOptOut,
            ..._body
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (callback != null) {
            _queryParams["callback"] = callback;
        }

        if (callbackMethod != null) {
            _queryParams["callback_method"] = callbackMethod;
        }

        if (extra != null) {
            if (Array.isArray(extra)) {
                _queryParams["extra"] = extra.map((item) => item);
            } else {
                _queryParams["extra"] = extra;
            }
        }

        if (sentiment != null) {
            _queryParams["sentiment"] = sentiment.toString();
        }

        if (summarize != null) {
            _queryParams["summarize"] = summarize;
        }

        if (tag != null) {
            if (Array.isArray(tag)) {
                _queryParams["tag"] = tag.map((item) => item);
            } else {
                _queryParams["tag"] = tag;
            }
        }

        if (topics != null) {
            _queryParams["topics"] = topics.toString();
        }

        if (customTopic != null) {
            if (Array.isArray(customTopic)) {
                _queryParams["custom_topic"] = customTopic.map((item) => item);
            } else {
                _queryParams["custom_topic"] = customTopic;
            }
        }

        if (customTopicMode != null) {
            _queryParams["custom_topic_mode"] = customTopicMode;
        }

        if (intents != null) {
            _queryParams["intents"] = intents.toString();
        }

        if (customIntent != null) {
            if (Array.isArray(customIntent)) {
                _queryParams["custom_intent"] = customIntent.map((item) => item);
            } else {
                _queryParams["custom_intent"] = customIntent;
            }
        }

        if (customIntentMode != null) {
            _queryParams["custom_intent_mode"] = customIntentMode;
        }

        if (detectEntities != null) {
            _queryParams["detect_entities"] = detectEntities.toString();
        }

        if (detectLanguage != null) {
            _queryParams["detect_language"] = detectLanguage.toString();
        }

        if (diarize != null) {
            _queryParams["diarize"] = diarize.toString();
        }

        if (dictation != null) {
            _queryParams["dictation"] = dictation.toString();
        }

        if (encoding != null) {
            _queryParams["encoding"] = encoding;
        }

        if (fillerWords != null) {
            _queryParams["filler_words"] = fillerWords.toString();
        }

        if (keyterm != null) {
            if (Array.isArray(keyterm)) {
                _queryParams["keyterm"] = keyterm.map((item) => item);
            } else {
                _queryParams["keyterm"] = keyterm;
            }
        }

        if (keywords != null) {
            if (Array.isArray(keywords)) {
                _queryParams["keywords"] = keywords.map((item) => item);
            } else {
                _queryParams["keywords"] = keywords;
            }
        }

        if (language != null) {
            _queryParams["language"] = language;
        }

        if (measurements != null) {
            _queryParams["measurements"] = measurements.toString();
        }

        if (model != null) {
            _queryParams["model"] = model;
        }

        if (multichannel != null) {
            _queryParams["multichannel"] = multichannel.toString();
        }

        if (numerals != null) {
            _queryParams["numerals"] = numerals.toString();
        }

        if (paragraphs != null) {
            _queryParams["paragraphs"] = paragraphs.toString();
        }

        if (profanityFilter != null) {
            _queryParams["profanity_filter"] = profanityFilter.toString();
        }

        if (punctuate != null) {
            _queryParams["punctuate"] = punctuate.toString();
        }

        if (redact != null) {
            _queryParams["redact"] = redact;
        }

        if (replace != null) {
            if (Array.isArray(replace)) {
                _queryParams["replace"] = replace.map((item) => item);
            } else {
                _queryParams["replace"] = replace;
            }
        }

        if (search != null) {
            if (Array.isArray(search)) {
                _queryParams["search"] = search.map((item) => item);
            } else {
                _queryParams["search"] = search;
            }
        }

        if (smartFormat != null) {
            _queryParams["smart_format"] = smartFormat.toString();
        }

        if (utterances != null) {
            _queryParams["utterances"] = utterances.toString();
        }

        if (uttSplit != null) {
            _queryParams["utt_split"] = uttSplit.toString();
        }

        if (version != null) {
            _queryParams["version"] = version;
        }

        if (mipOptOut != null) {
            _queryParams["mip_opt_out"] = mipOptOut.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                "v1/listen",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Deepgram.listen.v1.MediaTranscribeResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling POST /v1/listen.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Transcribe audio and video using Deepgram's speech-to-text REST API
     *
     * @param {core.file.Uploadable} uploadable
     * @param {Deepgram.listen.v1.MediaTranscribeRequestOctetStream} request
     * @param {Media.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.listen.v1.media.transcribeFile(createReadStream("path/to/file"), {})
     */
    public transcribeFile(
        uploadable: core.file.Uploadable,
        request: Deepgram.listen.v1.MediaTranscribeRequestOctetStream,
        requestOptions?: Media.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.listen.v1.MediaTranscribeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__transcribeFile(uploadable, request, requestOptions));
    }

    private async __transcribeFile(
        uploadable: core.file.Uploadable,
        request: Deepgram.listen.v1.MediaTranscribeRequestOctetStream,
        requestOptions?: Media.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.listen.v1.MediaTranscribeResponse>> {
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (request.callback != null) {
            _queryParams["callback"] = request.callback;
        }

        if (request.callback_method != null) {
            _queryParams["callback_method"] = request.callback_method;
        }

        if (request.extra != null) {
            if (Array.isArray(request.extra)) {
                _queryParams["extra"] = request.extra.map((item) => item);
            } else {
                _queryParams["extra"] = request.extra;
            }
        }

        if (request.sentiment != null) {
            _queryParams["sentiment"] = request.sentiment.toString();
        }

        if (request.summarize != null) {
            _queryParams["summarize"] = request.summarize;
        }

        if (request.tag != null) {
            if (Array.isArray(request.tag)) {
                _queryParams["tag"] = request.tag.map((item) => item);
            } else {
                _queryParams["tag"] = request.tag;
            }
        }

        if (request.topics != null) {
            _queryParams["topics"] = request.topics.toString();
        }

        if (request.custom_topic != null) {
            if (Array.isArray(request.custom_topic)) {
                _queryParams["custom_topic"] = request.custom_topic.map((item) => item);
            } else {
                _queryParams["custom_topic"] = request.custom_topic;
            }
        }

        if (request.custom_topic_mode != null) {
            _queryParams["custom_topic_mode"] = request.custom_topic_mode;
        }

        if (request.intents != null) {
            _queryParams["intents"] = request.intents.toString();
        }

        if (request.custom_intent != null) {
            if (Array.isArray(request.custom_intent)) {
                _queryParams["custom_intent"] = request.custom_intent.map((item) => item);
            } else {
                _queryParams["custom_intent"] = request.custom_intent;
            }
        }

        if (request.custom_intent_mode != null) {
            _queryParams["custom_intent_mode"] = request.custom_intent_mode;
        }

        if (request.detect_entities != null) {
            _queryParams["detect_entities"] = request.detect_entities.toString();
        }

        if (request.detect_language != null) {
            _queryParams["detect_language"] = request.detect_language.toString();
        }

        if (request.diarize != null) {
            _queryParams["diarize"] = request.diarize.toString();
        }

        if (request.dictation != null) {
            _queryParams["dictation"] = request.dictation.toString();
        }

        if (request.encoding != null) {
            _queryParams["encoding"] = request.encoding;
        }

        if (request.filler_words != null) {
            _queryParams["filler_words"] = request.filler_words.toString();
        }

        if (request.keyterm != null) {
            if (Array.isArray(request.keyterm)) {
                _queryParams["keyterm"] = request.keyterm.map((item) => item);
            } else {
                _queryParams["keyterm"] = request.keyterm;
            }
        }

        if (request.keywords != null) {
            if (Array.isArray(request.keywords)) {
                _queryParams["keywords"] = request.keywords.map((item) => item);
            } else {
                _queryParams["keywords"] = request.keywords;
            }
        }

        if (request.language != null) {
            _queryParams["language"] = request.language;
        }

        if (request.measurements != null) {
            _queryParams["measurements"] = request.measurements.toString();
        }

        if (request.model != null) {
            _queryParams["model"] = request.model;
        }

        if (request.multichannel != null) {
            _queryParams["multichannel"] = request.multichannel.toString();
        }

        if (request.numerals != null) {
            _queryParams["numerals"] = request.numerals.toString();
        }

        if (request.paragraphs != null) {
            _queryParams["paragraphs"] = request.paragraphs.toString();
        }

        if (request.profanity_filter != null) {
            _queryParams["profanity_filter"] = request.profanity_filter.toString();
        }

        if (request.punctuate != null) {
            _queryParams["punctuate"] = request.punctuate.toString();
        }

        if (request.redact != null) {
            _queryParams["redact"] = request.redact;
        }

        if (request.replace != null) {
            if (Array.isArray(request.replace)) {
                _queryParams["replace"] = request.replace.map((item) => item);
            } else {
                _queryParams["replace"] = request.replace;
            }
        }

        if (request.search != null) {
            if (Array.isArray(request.search)) {
                _queryParams["search"] = request.search.map((item) => item);
            } else {
                _queryParams["search"] = request.search;
            }
        }

        if (request.smart_format != null) {
            _queryParams["smart_format"] = request.smart_format.toString();
        }

        if (request.utterances != null) {
            _queryParams["utterances"] = request.utterances.toString();
        }

        if (request.utt_split != null) {
            _queryParams["utt_split"] = request.utt_split.toString();
        }

        if (request.version != null) {
            _queryParams["version"] = request.version;
        }

        if (request.mip_opt_out != null) {
            _queryParams["mip_opt_out"] = request.mip_opt_out.toString();
        }

        const _binaryUploadRequest = await core.file.toBinaryUploadRequest(uploadable);
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            _binaryUploadRequest.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                "v1/listen",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/octet-stream",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "bytes",
            duplex: "half",
            body: _binaryUploadRequest.body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Deepgram.listen.v1.MediaTranscribeResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling POST /v1/listen.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
