// This file was auto-generated by Fern from our API Definition.

export const KeysListRequestStatus = {
    Active: "active",
    Expired: "expired",
} as const;
export type KeysListRequestStatus = (typeof KeysListRequestStatus)[keyof typeof KeysListRequestStatus];
