/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type KeysListRequestStatus = "active" | "expired";
export const KeysListRequestStatus = {
    Active: "active",
    Expired: "expired",
} as const;
