// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import { BalancesClient } from "../resources/balances/client/Client.js";
import { BreakdownClient } from "../resources/breakdown/client/Client.js";
import { FieldsClient } from "../resources/fields/client/Client.js";
import { PurchasesClient } from "../resources/purchases/client/Client.js";

export declare namespace BillingClient {
    export interface Options extends BaseClientOptions {}
}

export class BillingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillingClient.Options>;
    protected _balances: BalancesClient | undefined;
    protected _breakdown: BreakdownClient | undefined;
    protected _fields: FieldsClient | undefined;
    protected _purchases: PurchasesClient | undefined;

    constructor(options: BillingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get balances(): BalancesClient {
        return (this._balances ??= new BalancesClient(this._options));
    }

    public get breakdown(): BreakdownClient {
        return (this._breakdown ??= new BreakdownClient(this._options));
    }

    public get fields(): FieldsClient {
        return (this._fields ??= new FieldsClient(this._options));
    }

    public get purchases(): PurchasesClient {
        return (this._purchases ??= new PurchasesClient(this._options));
    }
}
