/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Deepgram from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         provider: "quay"
 *     }
 */
export interface CreateProjectDistributionCredentialsV1Request {
    /** List of permission scopes for the credentials */
    scopes?:
        | Deepgram.selfHosted.v1.DistributionCredentialsCreateRequestScopesItem
        | Deepgram.selfHosted.v1.DistributionCredentialsCreateRequestScopesItem[];
    /** The provider of the distribution service */
    provider?: "quay";
    /** Optional comment about the credentials */
    comment?: string;
}
