// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../../../../../errors/index.js";
import * as Deepgram from "../../../../../../../../../../../index.js";

export declare namespace BreakdownClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BreakdownClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BreakdownClient.Options>;

    constructor(options: BreakdownClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves the usage breakdown for a specific project, with various filter options by API feature or by groupings. Setting a feature (e.g. diarize) to true includes requests that used that feature, while false excludes requests that used it. Multiple true filters are combined with OR logic, while false filters use AND logic.
     *
     * @param {string} project_id - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.usage.BreakdownGetRequest} request
     * @param {BreakdownClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.usage.breakdown.get("123456-7890-1234-5678-901234", {
     *         start: "start",
     *         end: "end",
     *         grouping: "accessor",
     *         accessor: "12345678-1234-1234-1234-123456789012",
     *         alternatives: true,
     *         callback_method: true,
     *         callback: true,
     *         channels: true,
     *         custom_intent_mode: true,
     *         custom_intent: true,
     *         custom_topic_mode: true,
     *         custom_topic: true,
     *         deployment: "hosted",
     *         detect_entities: true,
     *         detect_language: true,
     *         diarize: true,
     *         dictation: true,
     *         encoding: true,
     *         endpoint: "listen",
     *         extra: true,
     *         filler_words: true,
     *         intents: true,
     *         keyterm: true,
     *         keywords: true,
     *         language: true,
     *         measurements: true,
     *         method: "sync",
     *         model: "6f548761-c9c0-429a-9315-11a1d28499c8",
     *         multichannel: true,
     *         numerals: true,
     *         paragraphs: true,
     *         profanity_filter: true,
     *         punctuate: true,
     *         redact: true,
     *         replace: true,
     *         sample_rate: true,
     *         search: true,
     *         sentiment: true,
     *         smart_format: true,
     *         summarize: true,
     *         tag: "tag1",
     *         topics: true,
     *         utt_split: true,
     *         utterances: true,
     *         version: true
     *     })
     */
    public get(
        project_id: string,
        request: Deepgram.manage.v1.projects.usage.BreakdownGetRequest = {},
        requestOptions?: BreakdownClient.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.UsageBreakdownV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__get(project_id, request, requestOptions));
    }

    private async __get(
        project_id: string,
        request: Deepgram.manage.v1.projects.usage.BreakdownGetRequest = {},
        requestOptions?: BreakdownClient.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.UsageBreakdownV1Response>> {
        const {
            start,
            end,
            grouping,
            accessor,
            alternatives,
            callback_method: callbackMethod,
            callback,
            channels,
            custom_intent_mode: customIntentMode,
            custom_intent: customIntent,
            custom_topic_mode: customTopicMode,
            custom_topic: customTopic,
            deployment,
            detect_entities: detectEntities,
            detect_language: detectLanguage,
            diarize,
            dictation,
            encoding,
            endpoint,
            extra,
            filler_words: fillerWords,
            intents,
            keyterm,
            keywords,
            language,
            measurements,
            method,
            model,
            multichannel,
            numerals,
            paragraphs,
            profanity_filter: profanityFilter,
            punctuate,
            redact,
            replace,
            sample_rate: sampleRate,
            search,
            sentiment,
            smart_format: smartFormat,
            summarize,
            tag,
            topics,
            utt_split: uttSplit,
            utterances,
            version,
        } = request;
        const _queryParams: Record<string, unknown> = {
            start,
            end,
            grouping: grouping != null ? grouping : undefined,
            accessor,
            alternatives,
            callback_method: callbackMethod,
            callback,
            channels,
            custom_intent_mode: customIntentMode,
            custom_intent: customIntent,
            custom_topic_mode: customTopicMode,
            custom_topic: customTopic,
            deployment: deployment != null ? deployment : undefined,
            detect_entities: detectEntities,
            detect_language: detectLanguage,
            diarize,
            dictation,
            encoding,
            endpoint: endpoint != null ? endpoint : undefined,
            extra,
            filler_words: fillerWords,
            intents,
            keyterm,
            keywords,
            language,
            measurements,
            method: method != null ? method : undefined,
            model,
            multichannel,
            numerals,
            paragraphs,
            profanity_filter: profanityFilter,
            punctuate,
            redact,
            replace,
            sample_rate: sampleRate,
            search,
            sentiment,
            smart_format: smartFormat,
            summarize,
            tag,
            topics,
            utt_split: uttSplit,
            utterances,
            version,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DeepgramEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(project_id)}/usage/breakdown`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.UsageBreakdownV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{project_id}/usage/breakdown",
        );
    }
}
