// This file was auto-generated by Fern from our API Definition.

export const DiarizeModel = {
    Latest: "latest",
    V1: "v1",
} as const;
export type DiarizeModel = (typeof DiarizeModel)[keyof typeof DiarizeModel] | string;
