// This file was auto-generated by Fern from our API Definition.

export interface ListenV1Metadata {
    /** Message type identifier */
    type: "Metadata";
    /** The transaction key */
    transaction_key: string;
    /** The request ID */
    request_id: string;
    /** The sha256 */
    sha256: string;
    /** The created */
    created: string;
    /** The duration */
    duration: number;
    /** The channels */
    channels: number;
}
