// This file was auto-generated by Fern from our API Definition.

export interface ListenV1UtteranceEnd {
    /** Message type identifier */
    type: "UtteranceEnd";
    /** The channel */
    channel: number[];
    /** The last word end */
    last_word_end: number;
}
