// This file was auto-generated by Fern from our API Definition.

export interface ListenV1KeepAlive {
    /** Message type identifier */
    type: ListenV1KeepAlive.Type;
}

export namespace ListenV1KeepAlive {
    /** Message type identifier */
    export const Type = {
        Finalize: "Finalize",
        CloseStream: "CloseStream",
        KeepAlive: "KeepAlive",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type] | string;
}
