// This file was auto-generated by Fern from our API Definition.

export interface ListenV1Configure {
    /** Message type identifier */
    type: "Configure";
    /**
     * Replaces the stream's keyterms. Compatible with all Nova-3 models, monolingual and multilingual; on other
     * models the server returns an `Error` with code `KeytermsNotSupported`. Each array replaces the entire list,
     * including keyterms set with the `keyterm` query parameter. Send an empty array to clear all keyterms. Omit
     * the field, or set it to `null`, to keep the current keyterms.
     *
     * Each entry is a plain term or phrase with no weights or intensifiers. The 500-token keyterm limit that
     * applies to the `keyterm` query parameter also applies to each update. An over-limit update returns an
     * `Error`, and the stream keeps its previous keyterms.
     */
    keyterms?: string[] | undefined;
    /**
     * Turns formatting features on or off. Each key is a feature name and each value is a boolean, for
     * example `{"numerals": true}`.
     */
    features?: Record<string, boolean> | undefined;
}
