// This file was auto-generated by Fern from our API Definition.

export interface ListenV2Warning {
    /** Message type identifier */
    type: "Warning";
    /** The unique identifier of the request */
    request_id: string;
    /**
     * Starts at `0` and increments for each message the server sends
     * to the client. This includes messages of other types, like
     * `TurnInfo` messages.
     */
    sequence_id: number;
    /** Warning code identifying the condition, in `SCREAMING_SNAKE_CASE` */
    code: string;
    /** A human-readable description of the warning */
    description: string;
}
