/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListenV2FatalError {
    /** Message type identifier */
    type: "Error";
    /**
     * Starts at `0` and increments for each message the server sends
     * to the client.  This includes messages of other types, like
     * `Connected` messages.
     */
    sequence_id: number;
    /** A string code describing the error, e.g. `INTERNAL_SERVER_ERROR` */
    code: string;
    /** Prose description of the error */
    description: string;
}
