// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface ListenV2ConfigureSuccess {
    /** Message type identifier */
    type: "ConfigureSuccess";
    /** The unique identifier of the request */
    request_id: string;
    /**
     * Updates each parameter, if it is supplied. If a particular threshold parameter
     * is not supplied, the configuration continues using the currently configured value.
     */
    thresholds: ListenV2ConfigureSuccess.Thresholds;
    keyterms: Deepgram.ListenV2Keyterm;
    /**
     * Starts at `0` and increments for each message the server sends
     * to the client.  This includes messages of other types, like
     * `TurnInfo` messages.
     */
    sequence_id: number;
}

export namespace ListenV2ConfigureSuccess {
    /**
     * Updates each parameter, if it is supplied. If a particular threshold parameter
     * is not supplied, the configuration continues using the currently configured value.
     */
    export interface Thresholds {
        eager_eot_threshold?: Deepgram.ListenV2EagerEotThreshold | undefined;
        eot_threshold?: Deepgram.ListenV2EotThreshold | undefined;
        eot_timeout_ms?: Deepgram.ListenV2EotTimeoutMs | undefined;
    }
}
