// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface ListenV2Configure {
    /** Message type identifier */
    type: "Configure";
    /**
     * Updates each parameter, if it is supplied. If a particular threshold parameter
     * is not supplied, the configuration continues using the currently configured value.
     */
    thresholds?: ListenV2Configure.Thresholds | undefined;
    keyterms?: Deepgram.ListenV2Keyterm | undefined;
}

export namespace ListenV2Configure {
    /**
     * Updates each parameter, if it is supplied. If a particular threshold parameter
     * is not supplied, the configuration continues using the currently configured value.
     */
    export interface Thresholds {
        eager_eot_threshold?: Deepgram.ListenV2EagerEotThreshold | undefined;
        eot_threshold?: Deepgram.ListenV2EotThreshold | undefined;
        eot_timeout_ms?: Deepgram.ListenV2EotTimeoutMs | undefined;
    }
}
