// This file was auto-generated by Fern from our API Definition.

export interface ListenV2CloseStream {
    /** Message type identifier */
    type: ListenV2CloseStream.Type;
}

export namespace ListenV2CloseStream {
    /** Message type identifier */
    export const Type = {
        Finalize: "Finalize",
        CloseStream: "CloseStream",
        KeepAlive: "KeepAlive",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
