/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../../../mock-server/MockServerPool";
import { DeepgramClient } from "../../../../../../src/Client";
import * as Deepgram from "../../../../../../src/api/index";

describe("Fields", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = {
            tags: ["tag=dev", "tag=production"],
            models: [
                {
                    name: "2-medical-nova",
                    language: "en-MY",
                    version: "2024-05-31.13574",
                    model_id: "1234567890-12345-67890",
                },
            ],
            processing_methods: ["sync", "streaming"],
            features: ["alternatives", "detect_entities", "detect_language"],
        };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/usage/fields")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.usage.fields.list("123456-7890-1234-5678-901234", {
            start: "start",
            end: "end",
        });
        expect(response).toEqual({
            tags: ["tag=dev", "tag=production"],
            models: [
                {
                    name: "2-medical-nova",
                    language: "en-MY",
                    version: "2024-05-31.13574",
                    model_id: "1234567890-12345-67890",
                },
            ],
            processing_methods: ["sync", "streaming"],
            features: ["alternatives", "detect_entities", "detect_language"],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/usage/fields")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.usage.fields.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
