// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { V1Client } from "../resources/v1/client/Client.js";

export declare namespace AuthClient {
    export interface Options extends BaseClientOptions {}
}

export class AuthClient {
    protected readonly _options: AuthClient.Options;
    protected _v1: V1Client | undefined;

    constructor(options: AuthClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get v1(): V1Client {
        return (this._v1 ??= new V1Client(this._options));
    }
}
