// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { V1Client } from "../resources/v1/client/Client.js";

export declare namespace ReadClient {
    export interface Options extends BaseClientOptions {}
}

export class ReadClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ReadClient.Options>;
    protected _v1: V1Client | undefined;

    constructor(options: ReadClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get v1(): V1Client {
        return (this._v1 ??= new V1Client(this._options));
    }
}
