/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentThinkModelsV1Response {
    models: AgentThinkModelsV1Response.Models.Item[];
}

export namespace AgentThinkModelsV1Response {
    export type Models = Models.Item[];

    export namespace Models {
        export type Item =
            /**
             * OpenAI models */
            | {
                  id:
                      | "gpt-5"
                      | "gpt-5-mini"
                      | "gpt-5-nano"
                      | "gpt-4.1"
                      | "gpt-4.1-mini"
                      | "gpt-4.1-nano"
                      | "gpt-4o"
                      | "gpt-4o-mini";
                  name: string;
                  provider: "open_ai";
              }
            /**
             * Anthropic models */
            | {
                  id: "claude-3-5-haiku-latest" | "claude-sonnet-4-20250514";
                  name: string;
                  provider: "anthropic";
              }
            /**
             * Google models */
            | {
                  id: "gemini-2.5-flash" | "gemini-2.0-flash" | "gemini-2.0-flash-lite";
                  name: string;
                  provider: "google";
              }
            /**
             * Groq models */
            | {
                  id: "openai/gpt-oss-20b";
                  name: string;
                  provider: "groq";
              }
            /**
             * AWS Bedrock models (custom models accepted) */
            | {
                  id: string;
                  name: string;
                  provider: "aws_bedrock";
              };
    }
}
