// This file was auto-generated by Fern from our API Definition.

export interface Anthropic {
    type: "anthropic";
    /** The REST API version for the Anthropic Messages API */
    version?: "v1";
    /** Anthropic model to use */
    model: Anthropic.Model;
    /** Anthropic temperature (0-1) */
    temperature?: number;
}

export namespace Anthropic {
    /** Anthropic model to use */
    export const Model = {
        Claude35HaikuLatest: "claude-3-5-haiku-latest",
        ClaudeSonnet420250514: "claude-sonnet-4-20250514",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
}
