// This file was auto-generated by Fern from our API Definition.

export interface AwsBedrockThinkProvider {
    type: "aws_bedrock";
    /** AWS Bedrock model to use */
    model: AwsBedrockThinkProvider.Model;
    /** AWS Bedrock temperature (0-2) */
    temperature?: number;
    /** AWS credentials type (STS short-lived or IAM long-lived) */
    credentials?: AwsBedrockThinkProvider.Credentials;
}

export namespace AwsBedrockThinkProvider {
    /** AWS Bedrock model to use */
    export const Model = {
        AnthropicClaude35Sonnet20240620V10: "anthropic/claude-3-5-sonnet-20240620-v1:0",
        AnthropicClaude35Haiku20240307V10: "anthropic/claude-3-5-haiku-20240307-v1:0",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;

    /**
     * AWS credentials type (STS short-lived or IAM long-lived)
     */
    export interface Credentials {
        /** AWS credentials type (STS short-lived or IAM long-lived) */
        type?: Credentials.Type;
        /** AWS region */
        region?: string;
        /** AWS access key */
        access_key_id?: string;
        /** AWS secret access key */
        secret_access_key?: string;
        /** AWS session token (required for STS only) */
        session_token?: string;
    }

    export namespace Credentials {
        /** AWS credentials type (STS short-lived or IAM long-lived) */
        export const Type = {
            Sts: "sts",
            Iam: "iam",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type] | string;
    }
}
