// This file was auto-generated by Fern from our API Definition.

export interface Cartesia {
    type: "cartesia";
    /** The API version header for the Cartesia text-to-speech API */
    version?: "2025-03-17";
    /** Cartesia model ID */
    model_id: Cartesia.ModelId;
    voice: Cartesia.Voice;
    /** Cartesia language code */
    language?: string;
}

export namespace Cartesia {
    /** Cartesia model ID */
    export const ModelId = {
        Sonic2: "sonic-2",
        SonicMultilingual: "sonic-multilingual",
    } as const;
    export type ModelId = (typeof ModelId)[keyof typeof ModelId] | string;

    export interface Voice {
        /** Cartesia voice mode */
        mode: string;
        /** Cartesia voice ID */
        id: string;
    }
}
