/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateProjectDistributionCredentialsV1Response {
    member: CreateProjectDistributionCredentialsV1Response.Member;
    distribution_credentials: CreateProjectDistributionCredentialsV1Response.DistributionCredentials;
}

export namespace CreateProjectDistributionCredentialsV1Response {
    export interface Member {
        /** Unique identifier for the member */
        member_id: string;
        /** Email address of the member */
        email: string;
    }

    export interface DistributionCredentials {
        /** Unique identifier for the distribution credentials */
        distribution_credentials_id: string;
        /** The provider of the distribution service */
        provider: string;
        /** Optional comment about the credentials */
        comment?: string;
        /** List of permission scopes for the credentials */
        scopes: string[];
        /** Timestamp when the credentials were created */
        created: string;
    }
}
