// This file was auto-generated by Fern from our API Definition.

/**
 * Deepgram text-to-speech provider. Aura models use version v1 (default); Flux TTS uses version v2 and a flux-* model. Flux TTS is in Early Access — the Flux TTS-specific API surface and voice catalog may change before general availability.
 */
export interface Deepgram {
    type: "deepgram";
    /** The Deepgram text-to-speech model family. Accepted values: `v1` (Aura, the default) and `v2` (Flux TTS, Early Access). Use `v1` with an aura-* model and `v2` with a flux-* model. Defaults to `v1` when omitted. */
    version?: string | undefined;
    /** Deepgram TTS model. Aura models (version v1) use the aura-* voices; Flux TTS (version v2, Early Access) uses the flux-{voice}-{language} voices (e.g. flux-alexis-en). */
    model: Deepgram.Model;
    /** Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Not yet supported in all languages. */
    speed?: number | undefined;
}

export namespace Deepgram {
    /** Deepgram TTS model. Aura models (version v1) use the aura-* voices; Flux TTS (version v2, Early Access) uses the flux-{voice}-{language} voices (e.g. flux-alexis-en). */
    export const Model = {
        AuraAsteriaEn: "aura-asteria-en",
        AuraLunaEn: "aura-luna-en",
        AuraStellaEn: "aura-stella-en",
        AuraAthenaEn: "aura-athena-en",
        AuraHeraEn: "aura-hera-en",
        AuraOrionEn: "aura-orion-en",
        AuraArcasEn: "aura-arcas-en",
        AuraPerseusEn: "aura-perseus-en",
        AuraAngusEn: "aura-angus-en",
        AuraOrpheusEn: "aura-orpheus-en",
        AuraHeliosEn: "aura-helios-en",
        AuraZeusEn: "aura-zeus-en",
        Aura2AmaltheaEn: "aura-2-amalthea-en",
        Aura2AndromedaEn: "aura-2-andromeda-en",
        Aura2ApolloEn: "aura-2-apollo-en",
        Aura2ArcasEn: "aura-2-arcas-en",
        Aura2AriesEn: "aura-2-aries-en",
        Aura2AsteriaEn: "aura-2-asteria-en",
        Aura2AthenaEn: "aura-2-athena-en",
        Aura2AtlasEn: "aura-2-atlas-en",
        Aura2AuroraEn: "aura-2-aurora-en",
        Aura2CallistaEn: "aura-2-callista-en",
        Aura2CoraEn: "aura-2-cora-en",
        Aura2CordeliaEn: "aura-2-cordelia-en",
        Aura2DeliaEn: "aura-2-delia-en",
        Aura2DracoEn: "aura-2-draco-en",
        Aura2ElectraEn: "aura-2-electra-en",
        Aura2HarmoniaEn: "aura-2-harmonia-en",
        Aura2HelenaEn: "aura-2-helena-en",
        Aura2HeraEn: "aura-2-hera-en",
        Aura2HermesEn: "aura-2-hermes-en",
        Aura2HyperionEn: "aura-2-hyperion-en",
        Aura2IrisEn: "aura-2-iris-en",
        Aura2JanusEn: "aura-2-janus-en",
        Aura2JunoEn: "aura-2-juno-en",
        Aura2JupiterEn: "aura-2-jupiter-en",
        Aura2LunaEn: "aura-2-luna-en",
        Aura2MarsEn: "aura-2-mars-en",
        Aura2MinervaEn: "aura-2-minerva-en",
        Aura2NeptuneEn: "aura-2-neptune-en",
        Aura2OdysseusEn: "aura-2-odysseus-en",
        Aura2OpheliaEn: "aura-2-ophelia-en",
        Aura2OrionEn: "aura-2-orion-en",
        Aura2OrpheusEn: "aura-2-orpheus-en",
        Aura2PandoraEn: "aura-2-pandora-en",
        Aura2PhoebeEn: "aura-2-phoebe-en",
        Aura2PlutoEn: "aura-2-pluto-en",
        Aura2SaturnEn: "aura-2-saturn-en",
        Aura2SeleneEn: "aura-2-selene-en",
        Aura2ThaliaEn: "aura-2-thalia-en",
        Aura2TheiaEn: "aura-2-theia-en",
        Aura2VestaEn: "aura-2-vesta-en",
        Aura2ZeusEn: "aura-2-zeus-en",
        Aura2SirioEs: "aura-2-sirio-es",
        Aura2NestorEs: "aura-2-nestor-es",
        Aura2CarinaEs: "aura-2-carina-es",
        Aura2CelesteEs: "aura-2-celeste-es",
        Aura2AlvaroEs: "aura-2-alvaro-es",
        Aura2DianaEs: "aura-2-diana-es",
        Aura2AquilaEs: "aura-2-aquila-es",
        Aura2SelenaEs: "aura-2-selena-es",
        Aura2EstrellaEs: "aura-2-estrella-es",
        Aura2JavierEs: "aura-2-javier-es",
        FluxHaleyEn: "flux-haley-en",
        FluxHeatherEn: "flux-heather-en",
        FluxColeEn: "flux-cole-en",
        FluxAlexisEn: "flux-alexis-en",
        FluxPriyaEn: "flux-priya-en",
        FluxJackEn: "flux-jack-en",
        FluxBruceEn: "flux-bruce-en",
        FluxRufusEn: "flux-rufus-en",
        FluxDrewEn: "flux-drew-en",
        FluxReneeEn: "flux-renee-en",
        FluxMarcusEn: "flux-marcus-en",
        FluxSharonEn: "flux-sharon-en",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
}
