// This file was auto-generated by Fern from our API Definition.

export interface DeepgramListenProviderV2 {
    /** Provider type for speech-to-text */
    type: "deepgram";
    /** Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux) */
    version?: "v2" | undefined;
    /** Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi) */
    model: string;
    /** An array of one or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details. */
    language_hints?: string[] | undefined;
    /** Prompt keyterm recognition to improve Keyword Recall Rate */
    keyterms?: string[] | undefined;
}

// Backward-compat shim: the 2026-06-16 regen replaced the `language_hint`
// (`string | string[]`) field with `language_hints?: string[]` and dropped the
// `DeepgramListenProviderV2.LanguageHint` namespace type that Fern previously
// emitted. The nested `AgentV1SettingsAgentContextListenProviderV2.LanguageHint`
// alias and the compat-aliases regression test still reference this type, so we
// recreate it here and freeze the file in .fernignore. Mirrors the Python SDK's
// DeepgramListenProviderV2LanguageHint shim.
export namespace DeepgramListenProviderV2 {
    /**
     * One or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.
     */
    export type LanguageHint = string | string[];
}
