// This file was auto-generated by Fern from our API Definition.

export interface DeepgramListenProviderV1 {
    /** Provider type for speech-to-text */
    type: "deepgram";
    /** Specifies usage of the V1 Deepgram speech-to-text API */
    version?: "v1" | undefined;
    /** Model to use for speech to text using the V1 API (e.g. Nova-3, Nova-2) */
    model?: string | undefined;
    /** Language code to use for speech-to-text. Can be a BCP-47 language tag (e.g. `en`), or `multi` for code-switching transcription */
    language?: string | undefined;
    /** Prompt keyterm recognition to improve Keyword Recall Rate */
    keyterms?: string[] | undefined;
    /** Applies smart formatting to improve transcript readability */
    smart_format?: boolean | undefined;
}
