// This file was auto-generated by Fern from our API Definition.

/**
 * Deepgram text-to-speech provider. Aura models use version v1 (default); Flux TTS uses version v2 and a flux-* model. Flux TTS is the default when agent.speak is omitted, using the flux-kit-en voice.
 */
export interface Deepgram {
    type: "deepgram";
    /** The Deepgram text-to-speech model family. Accepted values: `v1` (Aura, the default) and `v2` (Flux TTS). Use `v1` with an aura-* model and `v2` with a flux-* model. Defaults to `v1` when omitted. */
    version?: string | undefined;
    /** Deepgram TTS model. Aura models (version v1) use the aura-* voices; Flux TTS (version v2) uses the flux-{voice}-{language} voices (e.g. flux-alexis-en). Defaults to flux-kit-en when agent.speak is omitted. */
    model: Deepgram.Model;
    /** Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Aura (version v1) accepts any value from 0.7 to 1.5. Flux TTS (version v2) accepts only 0.85, 0.9, 0.95, 1.0, 1.05, 1.1 and 1.15; another value ends the session with FAILED_TO_SPEAK. Not yet supported in all languages. */
    speed?: number | undefined;
}

export namespace Deepgram {
    /** Deepgram TTS model. Aura models (version v1) use the aura-* voices; Flux TTS (version v2) uses the flux-{voice}-{language} voices (e.g. flux-alexis-en). Defaults to flux-kit-en when agent.speak is omitted. */
    export const Model = {
        AuraAsteriaEn: "aura-asteria-en",
        AuraLunaEn: "aura-luna-en",
        AuraStellaEn: "aura-stella-en",
        AuraAthenaEn: "aura-athena-en",
        AuraHeraEn: "aura-hera-en",
        AuraOrionEn: "aura-orion-en",
        AuraArcasEn: "aura-arcas-en",
        AuraPerseusEn: "aura-perseus-en",
        AuraAngusEn: "aura-angus-en",
        AuraOrpheusEn: "aura-orpheus-en",
        AuraHeliosEn: "aura-helios-en",
        AuraZeusEn: "aura-zeus-en",
        Aura2AmaltheaEn: "aura-2-amalthea-en",
        Aura2AndromedaEn: "aura-2-andromeda-en",
        Aura2ApolloEn: "aura-2-apollo-en",
        Aura2ArcasEn: "aura-2-arcas-en",
        Aura2AriesEn: "aura-2-aries-en",
        Aura2AsteriaEn: "aura-2-asteria-en",
        Aura2AthenaEn: "aura-2-athena-en",
        Aura2AtlasEn: "aura-2-atlas-en",
        Aura2AuroraEn: "aura-2-aurora-en",
        Aura2CallistaEn: "aura-2-callista-en",
        Aura2CoraEn: "aura-2-cora-en",
        Aura2CordeliaEn: "aura-2-cordelia-en",
        Aura2DeliaEn: "aura-2-delia-en",
        Aura2DracoEn: "aura-2-draco-en",
        Aura2ElectraEn: "aura-2-electra-en",
        Aura2HarmoniaEn: "aura-2-harmonia-en",
        Aura2HelenaEn: "aura-2-helena-en",
        Aura2HeraEn: "aura-2-hera-en",
        Aura2HermesEn: "aura-2-hermes-en",
        Aura2HyperionEn: "aura-2-hyperion-en",
        Aura2IrisEn: "aura-2-iris-en",
        Aura2JanusEn: "aura-2-janus-en",
        Aura2JunoEn: "aura-2-juno-en",
        Aura2JupiterEn: "aura-2-jupiter-en",
        Aura2LunaEn: "aura-2-luna-en",
        Aura2MarsEn: "aura-2-mars-en",
        Aura2MinervaEn: "aura-2-minerva-en",
        Aura2NeptuneEn: "aura-2-neptune-en",
        Aura2OdysseusEn: "aura-2-odysseus-en",
        Aura2OpheliaEn: "aura-2-ophelia-en",
        Aura2OrionEn: "aura-2-orion-en",
        Aura2OrpheusEn: "aura-2-orpheus-en",
        Aura2PandoraEn: "aura-2-pandora-en",
        Aura2PhoebeEn: "aura-2-phoebe-en",
        Aura2PlutoEn: "aura-2-pluto-en",
        Aura2SaturnEn: "aura-2-saturn-en",
        Aura2SeleneEn: "aura-2-selene-en",
        Aura2ThaliaEn: "aura-2-thalia-en",
        Aura2TheiaEn: "aura-2-theia-en",
        Aura2VestaEn: "aura-2-vesta-en",
        Aura2ZeusEn: "aura-2-zeus-en",
        Aura2SirioEs: "aura-2-sirio-es",
        Aura2NestorEs: "aura-2-nestor-es",
        Aura2CarinaEs: "aura-2-carina-es",
        Aura2CelesteEs: "aura-2-celeste-es",
        Aura2AlvaroEs: "aura-2-alvaro-es",
        Aura2DianaEs: "aura-2-diana-es",
        Aura2AquilaEs: "aura-2-aquila-es",
        Aura2SelenaEs: "aura-2-selena-es",
        Aura2EstrellaEs: "aura-2-estrella-es",
        Aura2JavierEs: "aura-2-javier-es",
        FluxAlexisEn: "flux-alexis-en",
        FluxBreeEn: "flux-bree-en",
        FluxBrittanyEn: "flux-brittany-en",
        FluxBrookeEn: "flux-brooke-en",
        FluxBruceEn: "flux-bruce-en",
        FluxCliffEn: "flux-cliff-en",
        FluxColeEn: "flux-cole-en",
        FluxColinEn: "flux-colin-en",
        FluxConorEn: "flux-conor-en",
        FluxDonovanEn: "flux-donovan-en",
        FluxDrewEn: "flux-drew-en",
        FluxEliseEn: "flux-elise-en",
        FluxGemmaEn: "flux-gemma-en",
        FluxHaleyEn: "flux-haley-en",
        FluxHannahEn: "flux-hannah-en",
        FluxHeatherEn: "flux-heather-en",
        FluxJackEn: "flux-jack-en",
        FluxKaiEn: "flux-kai-en",
        FluxKelseyEn: "flux-kelsey-en",
        FluxKitEn: "flux-kit-en",
        FluxMaeveEn: "flux-maeve-en",
        FluxMarceloEn: "flux-marcelo-en",
        FluxMarcusEn: "flux-marcus-en",
        FluxMeenaEn: "flux-meena-en",
        FluxMeghanEn: "flux-meghan-en",
        FluxMilesEn: "flux-miles-en",
        FluxNaveenEn: "flux-naveen-en",
        FluxPaigeEn: "flux-paige-en",
        FluxPriyaEn: "flux-priya-en",
        /**
         * @deprecated Removed from the published Flux TTS voice catalog in the GA cutover
         * (deepgram-docs #1096, 2026-08-12). Retained here for backward compatibility: the
         * voice was still synthesizing normally when this was verified on 2026-08-19, so
         * dropping the constant would break callers whose code still works at runtime.
         * It is no longer a documented voice and may be withdrawn without notice — prefer
         * a voice from the GA catalog.
         */
        FluxReneeEn: "flux-renee-en",
        FluxRufusEn: "flux-rufus-en",
        FluxSeanEn: "flux-sean-en",
        FluxSharonEn: "flux-sharon-en",
        FluxSiennaEn: "flux-sienna-en",
        FluxTannerEn: "flux-tanner-en",
        FluxWadeEn: "flux-wade-en",
        FluxWesEn: "flux-wes-en",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
}
