/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorResponseModernError {
    /** The category of the error */
    category?: string;
    /** A message about the error */
    message?: string;
    /** A description of the error */
    details?: string;
    /** The unique identifier of the request */
    request_id?: string;
}
