// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../index.js";

export type ErrorResponse =
    | Deepgram.ErrorResponseTextError
    | Deepgram.ErrorResponseLegacyError
    | Deepgram.ErrorResponseModernError;
