/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetModelV1Response =
    | {
          name?: string | undefined;
          canonical_name?: string | undefined;
          architecture?: string | undefined;
          languages?: string[] | undefined;
          version?: string | undefined;
          uuid?: string | undefined;
          batch?: boolean | undefined;
          streaming?: boolean | undefined;
          formatted_output?: boolean | undefined;
      }
    | {
          name?: string | undefined;
          canonical_name?: string | undefined;
          architecture?: string | undefined;
          languages?: string[] | undefined;
          version?: string | undefined;
          uuid?: string | undefined;
          metadata?:
              | {
                    accent?: string | undefined;
                    age?: string | undefined;
                    color?: string | undefined;
                    image?: string | undefined;
                    sample?: string | undefined;
                    tags?: string[] | undefined;
                    use_cases?: string[] | undefined;
                }
              | undefined;
      };
