/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetProjectBalanceV1Response {
    /** The unique identifier of the balance */
    balance_id?: string;
    /** The amount of the balance */
    amount?: number;
    /** The units of the balance, such as "USD" */
    units?: string;
    /** Description or reference of the purchase */
    purchase_order_id?: string;
}
