// This file was auto-generated by Fern from our API Definition.

export interface Google {
    type: "google";
    /** The REST API version for the Google generative language API */
    version?: "v1beta";
    /** Google model to use */
    model: Google.Model;
    /** Google temperature (0-2) */
    temperature?: number;
}

export namespace Google {
    /** Google model to use */
    export const Model = {
        Gemini20Flash: "gemini-2.0-flash",
        Gemini20FlashLite: "gemini-2.0-flash-lite",
        Gemini25Flash: "gemini-2.5-flash",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
}
