/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Deepgram from "../index.js";

export interface ListenV1ResponseResults {
    channels: Deepgram.ListenV1ResponseResultsChannels;
    utterances?: Deepgram.ListenV1ResponseResultsUtterances;
    summary?: Deepgram.ListenV1ResponseResultsSummary;
    topics?: Deepgram.SharedTopics;
    intents?: Deepgram.SharedIntents;
    sentiments?: Deepgram.SharedSentiments;
}
