// This file was auto-generated by Fern from our API Definition.

/** Transcribe each audio channel independently */
export const ListenV1Multichannel = {
    True: "true",
    False: "false",
} as const;
export type ListenV1Multichannel = (typeof ListenV1Multichannel)[keyof typeof ListenV1Multichannel] | string;
