/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identify and extract key entities from content in submitted audio
 */
export type ListenV1Dictation = "true" | "false";
export const ListenV1Dictation = {
    True: "true",
    False: "false",
} as const;
