// This file was auto-generated by Fern from our API Definition.

/** Specify the expected encoding of your submitted audio */
export const ListenV1Encoding = {
    Linear16: "linear16",
    Linear32: "linear32",
    Flac: "flac",
    Alaw: "alaw",
    Mulaw: "mulaw",
    AmrNb: "amr-nb",
    AmrWb: "amr-wb",
    Opus: "opus",
    OggOpus: "ogg-opus",
    Speex: "speex",
    G729: "g729",
} as const;
export type ListenV1Encoding = (typeof ListenV1Encoding)[keyof typeof ListenV1Encoding] | string;
