/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies whether the streaming endpoint should provide ongoing transcription updates as more audio is received. When set to true, the endpoint sends continuous updates, meaning transcription results may evolve over time
 */
export type ListenV1InterimResults = "true" | "false";
export const ListenV1InterimResults = {
    True: "true",
    False: "false",
} as const;
