// This file was auto-generated by Fern from our API Definition.

/**
 * Key term prompting can boost specialized terminology and brands. Only compatible with Nova-3
 */
export type ListenV1Keyterm = unknown;
