// This file was auto-generated by Fern from our API Definition.

export interface ListProjectInvitesV1Response {
    invites?: ListProjectInvitesV1Response.Invites.Item[];
}

export namespace ListProjectInvitesV1Response {
    export type Invites = Invites.Item[];

    export namespace Invites {
        export interface Item {
            /** The email address of the invitee */
            email?: string;
            /** The scope of the invitee */
            scope?: string;
        }
    }
}
