// This file was auto-generated by Fern from our API Definition.

/**
 * Keywords can boost or suppress specialized terminology and brands. `keywords` is not supported with Nova-3 models; use `keyterm` instead.
 */
export type ListenV1Keywords = unknown;
