// This file was auto-generated by Fern from our API Definition.

export interface ListProjectMembersV1Response {
    members?: ListProjectMembersV1Response.Members.Item[];
}

export namespace ListProjectMembersV1Response {
    export type Members = Members.Item[];

    export namespace Members {
        export interface Item {
            /** The unique identifier of the member */
            member_id?: string;
            email?: string;
        }
    }
}
