// This file was auto-generated by Fern from our API Definition.

/**
 * End-of-turn confidence required to fire an eager end-of-turn event.
 * When set, enables `EagerEndOfTurn` and `TurnResumed` events. Valid
 * Values 0.3 - 0.9.
 */
export type ListenV2EagerEotThreshold = unknown;
