// This file was auto-generated by Fern from our API Definition.

export interface ListenV1ResponseMetadata {
    transaction_key?: string;
    request_id: string;
    sha256: string;
    created: string;
    duration: number;
    channels: number;
    models: string[];
    model_info: Record<string, unknown>;
    summary_info?: ListenV1ResponseMetadata.SummaryInfo;
    sentiment_info?: ListenV1ResponseMetadata.SentimentInfo;
    topics_info?: ListenV1ResponseMetadata.TopicsInfo;
    intents_info?: ListenV1ResponseMetadata.IntentsInfo;
    tags?: string[];
}

export namespace ListenV1ResponseMetadata {
    export interface SummaryInfo {
        model_uuid?: string;
        input_tokens?: number;
        output_tokens?: number;
    }

    export interface SentimentInfo {
        model_uuid?: string;
        input_tokens?: number;
        output_tokens?: number;
    }

    export interface TopicsInfo {
        model_uuid?: string;
        input_tokens?: number;
        output_tokens?: number;
    }

    export interface IntentsInfo {
        model_uuid?: string;
        input_tokens?: number;
        output_tokens?: number;
    }
}
