// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../index.js";

export interface ListModelsV1Response {
    stt?: Deepgram.ListModelsV1ResponseSttModels[];
    tts?: Deepgram.ListModelsV1ResponseTtsModels[];
}
