// This file was auto-generated by Fern from our API Definition.

/** Identifies and extracts key entities from content in submitted audio. Entities appear in final results. When enabled, Punctuation will also be enabled by default */
export const ListenV1DetectEntities = {
    True: "true",
    False: "false",
} as const;
export type ListenV1DetectEntities = (typeof ListenV1DetectEntities)[keyof typeof ListenV1DetectEntities] | string;
