// This file was auto-generated by Fern from our API Definition.

export interface ListProjectBalancesV1Response {
    balances?: ListProjectBalancesV1Response.Balances.Item[] | undefined;
}

export namespace ListProjectBalancesV1Response {
    export type Balances = Balances.Item[];

    export namespace Balances {
        export interface Item {
            /** The unique identifier of the balance */
            balance_id?: string | undefined;
            /** The amount of the balance */
            amount?: number | undefined;
            /** The units of the balance, such as "USD" */
            units?: string | undefined;
            /** Description or reference of the purchase */
            purchase_order_id?: string | undefined;
        }
    }
}
