// This file was auto-generated by Fern from our API Definition.

/**
 * Sample rate of the audio stream in Hz. Required if sending non-containerized/raw audio. If sending containerized audio, this parameter should be omitted.
 */
export type ListenV2SampleRate = unknown;
