// This file was auto-generated by Fern from our API Definition.

/** Profanity Filter looks for recognized profanity and converts it to the nearest recognized non-profane word or removes it from the transcript completely */
export const ListenV1ProfanityFilter = {
    True: "true",
    False: "false",
} as const;
export type ListenV1ProfanityFilter = (typeof ListenV1ProfanityFilter)[keyof typeof ListenV1ProfanityFilter] | string;
