// This file was auto-generated by Fern from our API Definition.

export interface ListBillingFieldsV1Response {
    /** List of accessor UUIDs for the time period */
    accessors?: string[] | undefined;
    /** List of deployment types for the time period */
    deployments?: ListBillingFieldsV1Response.Deployments.Item[] | undefined;
    /** List of tags for the time period */
    tags?: string[] | undefined;
    /** Map of line item names to human-readable descriptions for the time period */
    line_items?: Record<string, string> | undefined;
}

export namespace ListBillingFieldsV1Response {
    export type Deployments = Deployments.Item[];

    export namespace Deployments {
        export const Item = {
            Hosted: "hosted",
            Beta: "beta",
            SelfHosted: "self-hosted",
            Dedicated: "dedicated",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item] | string;
    }
}
