/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListProjectDistributionCredentialsV1Response {
    /** Array of distribution credentials with associated member information */
    distribution_credentials?: ListProjectDistributionCredentialsV1Response.DistributionCredentials.Item[];
}

export namespace ListProjectDistributionCredentialsV1Response {
    export type DistributionCredentials = DistributionCredentials.Item[];

    export namespace DistributionCredentials {
        export interface Item {
            member: Item.Member;
            distribution_credentials: Item.DistributionCredentials;
        }

        export namespace Item {
            export interface Member {
                /** Unique identifier for the member */
                member_id: string;
                /** Email address of the member */
                email: string;
            }

            export interface DistributionCredentials {
                /** Unique identifier for the distribution credentials */
                distribution_credentials_id: string;
                /** The provider of the distribution service */
                provider: string;
                /** Optional comment about the credentials */
                comment?: string;
                /** List of permission scopes for the credentials */
                scopes: string[];
                /** Timestamp when the credentials were created */
                created: string;
            }
        }
    }
}
