// This file was auto-generated by Fern from our API Definition.

/**
 * Language hints constrain and prioritize language detection for the
 * flux-general-multi model. Pass multiple language_hint query parameters
 * to specify multiple language codes. Empty values are rejected.
 * Only valid when model is flux-general-multi.
 */
export type ListenV2LanguageHint = string | string[];
