/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates that speech has started. You'll begin receiving Speech Started messages upon speech starting
 */
export type ListenV1VadEvents = "true" | "false";
export const ListenV1VadEvents = {
    True: "true",
    False: "false",
} as const;
