/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HTTP method by which the callback request will be made
 */
export type ListenV1CallbackMethod = "POST" | "GET" | "PUT" | "DELETE";
export const ListenV1CallbackMethod = {
    Post: "POST",
    Get: "GET",
    Put: "PUT",
    Delete: "DELETE",
} as const;
