/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Accepted response for asynchronous transcription requests
 */
export interface ListenV1AcceptedResponse {
    /** Unique identifier for tracking the asynchronous request */
    request_id: string;
}
