// This file was auto-generated by Fern from our API Definition.

/** Redaction removes sensitive information from your transcripts. On Flux, only `numbers` and `aggressive_numbers` are supported. */
export const ListenV2Redact = {
    Numbers: "numbers",
    AggressiveNumbers: "aggressive_numbers",
} as const;
export type ListenV2Redact = (typeof ListenV2Redact)[keyof typeof ListenV2Redact] | string;
