// This file was auto-generated by Fern from our API Definition.

/** Profanity Filter looks for recognized profanity and converts it to the nearest recognized non-profane word or removes it from the transcript completely. */
export const ListenV2ProfanityFilter = {
    True: "true",
    False: "false",
} as const;
export type ListenV2ProfanityFilter = (typeof ListenV2ProfanityFilter)[keyof typeof ListenV2ProfanityFilter] | string;
