/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Transcribe each audio channel independently
 */
export type ListenV1Multichannel = "true" | "false";
export const ListenV1Multichannel = {
    True: "true",
    False: "false",
} as const;
