// This file was auto-generated by Fern from our API Definition.

export interface ListModelsV1ResponseTtsModels {
    name?: string | undefined;
    canonical_name?: string | undefined;
    architecture?: string | undefined;
    languages?: string[] | undefined;
    version?: string | undefined;
    uuid?: string | undefined;
    metadata?: ListModelsV1ResponseTtsModels.Metadata | undefined;
}

export namespace ListModelsV1ResponseTtsModels {
    export interface Metadata {
        accent?: string | undefined;
        age?: string | undefined;
        color?: string | undefined;
        image?: string | undefined;
        sample?: string | undefined;
        tags?: string[] | undefined;
        use_cases?: string[] | undefined;
    }
}
