// This file was auto-generated by Fern from our API Definition.

export interface ListProjectPurchasesV1Response {
    orders?: ListProjectPurchasesV1Response.Orders.Item[];
}

export namespace ListProjectPurchasesV1Response {
    export type Orders = Orders.Item[];

    export namespace Orders {
        export interface Item {
            order_id?: string;
            expiration?: string;
            created?: string;
            amount?: number;
            units?: string;
            order_type?: string;
        }
    }
}
