/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Add punctuation and capitalization to the transcript
 */
export type ListenV1Punctuate = "true" | "false";
export const ListenV1Punctuate = {
    True: "true",
    False: "false",
} as const;
