// This file was auto-generated by Fern from our API Definition.

/**
 * Arbitrary key-value pairs that are attached to the API response for usage in downstream processing
 */
export type ListenV1Extra = unknown;
