// This file was auto-generated by Fern from our API Definition.

/** Encoding of the audio stream. Required if sending non-containerized/raw audio. If sending containerized audio, this parameter should be omitted. */
export const ListenV2Encoding = {
    Linear16: "linear16",
    Linear32: "linear32",
    Mulaw: "mulaw",
    Alaw: "alaw",
    Opus: "opus",
    OggOpus: "ogg-opus",
} as const;
export type ListenV2Encoding = (typeof ListenV2Encoding)[keyof typeof ListenV2Encoding] | string;
