// This file was auto-generated by Fern from our API Definition.

export interface OpenAi {
    type: "open_ai";
    /** The REST API version for the OpenAI text-to-speech API */
    version?: "v1";
    /** OpenAI TTS model */
    model: OpenAi.Model;
    /** OpenAI voice */
    voice: OpenAi.Voice;
}

export namespace OpenAi {
    /** OpenAI TTS model */
    export const Model = {
        Tts1: "tts-1",
        Tts1Hd: "tts-1-hd",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
    /** OpenAI voice */
    export const Voice = {
        Alloy: "alloy",
        Echo: "echo",
        Fable: "fable",
        Onyx: "onyx",
        Nova: "nova",
        Shimmer: "shimmer",
    } as const;
    export type Voice = (typeof Voice)[keyof typeof Voice] | string;
}
