// This file was auto-generated by Fern from our API Definition.

export interface OpenAiThinkProvider {
    type: "open_ai";
    /** The REST API version for the OpenAI chat completions API */
    version?: "v1" | undefined;
    /** OpenAI model to use */
    model: OpenAiThinkProvider.Model;
    /** OpenAI temperature (0-2) */
    temperature?: number | undefined;
    /** OpenAI reasoning_effort */
    reasoning_mode?: OpenAiThinkProvider.ReasoningMode | undefined;
}

export namespace OpenAiThinkProvider {
    /** OpenAI model to use */
    export const Model = {
        Gpt5: "gpt-5",
        Gpt5Mini: "gpt-5-mini",
        Gpt5Nano: "gpt-5-nano",
        Gpt41: "gpt-4.1",
        Gpt41Mini: "gpt-4.1-mini",
        Gpt41Nano: "gpt-4.1-nano",
        Gpt4O: "gpt-4o",
        Gpt4OMini: "gpt-4o-mini",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
    /** OpenAI reasoning_effort */
    export const ReasoningMode = {
        None: "none",
        Minimal: "minimal",
        Low: "low",
        Medium: "medium",
        High: "high",
    } as const;
    export type ReasoningMode = (typeof ReasoningMode)[keyof typeof ReasoningMode] | string;
}
