// This file was auto-generated by Fern from our API Definition.

export interface OpenAiThinkProvider {
    type: "open_ai";
    /** The REST API version for the OpenAI chat completions API */
    version?: "v1";
    /** OpenAI model to use */
    model: OpenAiThinkProvider.Model;
    /** OpenAI temperature (0-2) */
    temperature?: number;
}

export namespace OpenAiThinkProvider {
    /** OpenAI model to use */
    export const Model = {
        Gpt5: "gpt-5",
        Gpt5Mini: "gpt-5-mini",
        Gpt5Nano: "gpt-5-nano",
        Gpt41: "gpt-4.1",
        Gpt41Mini: "gpt-4.1-mini",
        Gpt41Nano: "gpt-4.1-nano",
        Gpt4O: "gpt-4o",
        Gpt4OMini: "gpt-4o-mini",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model] | string;
}
