// This file was auto-generated by Fern from our API Definition.

/**
 * A single request
 */
export interface ProjectRequestResponse {
    /** The unique identifier of the request */
    request_id?: string | undefined;
    /** The unique identifier of the project */
    project_uuid?: string | undefined;
    /** The date and time the request was created */
    created?: string | undefined;
    /** The API path of the request */
    path?: string | undefined;
    /** The unique identifier of the API key */
    api_key_id?: string | undefined;
    /** The response of the request */
    response?: Record<string, unknown> | undefined;
    /** The response code of the request */
    code?: number | undefined;
    /** The deployment type */
    deployment?: string | undefined;
    /** The callback URL for the request */
    callback?: string | undefined;
}
