// This file was auto-generated by Fern from our API Definition.

/**
 * Output whenever `sentiment=true` is used
 */
export interface SharedSentiments {
    segments?: SharedSentiments.Segments.Item[] | undefined;
    average?: SharedSentiments.Average | undefined;
}

export namespace SharedSentiments {
    export type Segments = Segments.Item[];

    export namespace Segments {
        export interface Item {
            text?: string | undefined;
            start_word?: number | undefined;
            end_word?: number | undefined;
            sentiment?: string | undefined;
            sentiment_score?: number | undefined;
        }
    }

    export interface Average {
        sentiment?: string | undefined;
        sentiment_score?: number | undefined;
    }
}
