// This file was auto-generated by Fern from our API Definition.

/** Speech-rate multiplier. `1.00` is the model's nominal rate; lower is slower. Accepted values: `0.85`, `0.90`, `0.95`, `1.00`, `1.05`, `1.10`, `1.15`. A value outside that range is rejected with `SPEED_OUT_OF_RANGE`; a value inside it but off the `0.05` increment with `SPEED_INCREMENT_INVALID`. Models and languages without runtime speed control reject any value with `SPEED_NOT_SUPPORTED`. */
export const SpeakV2Speed = {
    ZeroPointEightFive: "0.85",
    ZeroPointNine: "0.90",
    ZeroPointNineFive: "0.95",
    One: "1.00",
    OnePointZeroFive: "1.05",
    OnePointOne: "1.10",
    OnePointOneFive: "1.15",
} as const;
// Backward-compat shim: before the 2026-08-19 regen this type was plain `number`,
// and `speed` shipped as a numeric connect param in 5.8.0 — so `speak.v2.connect({
// speed: 1.0 })` is live in caller code. The regen narrowed it to a string enum
// (while repointing `SpeakV2Configure.speed` at the new numeric `SpeakV2SpeedValue`,
// leaving the same concept typed two ways). We keep the generated constants but
// widen the type back to admit `number` so numeric call sites keep compiling.
// `speed` is a query param on the websocket connect, so numbers and the equivalent
// strings serialize identically — this is compile-compat only, no wire change.
// Regression coverage in tests/unit/regen-constraints.test.ts.
export type SpeakV2Speed = (typeof SpeakV2Speed)[keyof typeof SpeakV2Speed] | string | number;
