// This file was auto-generated by Fern from our API Definition.

/**
 * Expressive range of the generated speech. `0` is the voice's nominal delivery; negative values are flatter and more restrained, positive values more animated.
 */
export type SpeakV2Expressivity = number;
