// This file was auto-generated by Fern from our API Definition.

/** Output sample rate in Hz. With `linear16`, valid values are `8000`, `16000`, `24000`, `32000`, `44100`, and `48000`. With `mulaw` or `alaw`, valid values are `8000` and `16000`. Defaults to the model's native sample rate. */
export const SpeakV2SampleRate = {
    EightThousand: "8000",
    SixteenThousand: "16000",
    TwentyFourThousand: "24000",
    ThirtyTwoThousand: "32000",
    FortyFourThousandOneHundred: "44100",
    FortyEightThousand: "48000",
} as const;
export type SpeakV2SampleRate = (typeof SpeakV2SampleRate)[keyof typeof SpeakV2SampleRate] | string;
