/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UsageV1Response {
    start?: string;
    end?: string;
    resolution?: UsageV1Response.Resolution;
}

export namespace UsageV1Response {
    export interface Resolution {
        units?: string;
        amount?: number;
    }
}
