// This file was auto-generated by Fern from our API Definition.

export interface UsageFieldsV1Response {
    /** List of tags associated with the project */
    tags?: string[] | undefined;
    /** List of models available for the project. */
    models?: UsageFieldsV1Response.Models.Item[] | undefined;
    /** Processing methods supported by the API */
    processing_methods?: string[] | undefined;
    /** API features available to the project */
    features?: string[] | undefined;
}

export namespace UsageFieldsV1Response {
    export type Models = Models.Item[];

    export namespace Models {
        export interface Item {
            /** Name of the model. */
            name?: string | undefined;
            /** The language supported by the model (IETF language tag). */
            language?: string | undefined;
            /** Version identifier of the model, typically with a date and a revision number. */
            version?: string | undefined;
            /** Unique identifier for the model. */
            model_id?: string | undefined;
        }
    }
}
