/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UsageBreakdownV1Response {
    /** Start date of the usage period */
    start: string;
    /** End date of the usage period */
    end: string;
    resolution: UsageBreakdownV1Response.Resolution;
    results: UsageBreakdownV1Response.Results.Item[];
}

export namespace UsageBreakdownV1Response {
    export interface Resolution {
        /** Time unit for the resolution */
        units: string;
        /** Amount of units */
        amount: number;
    }

    export type Results = Results.Item[];

    export namespace Results {
        export interface Item {
            /** Audio hours processed */
            hours: number;
            /** Total hours including all processing */
            total_hours: number;
            /** Agent hours used */
            agent_hours: number;
            /** Number of input tokens */
            tokens_in: number;
            /** Number of output tokens */
            tokens_out: number;
            /** Number of text-to-speech characters processed */
            tts_characters: number;
            /** Number of requests */
            requests: number;
            grouping: Item.Grouping;
        }

        export namespace Item {
            export interface Grouping {
                /** Start date for this group */
                start?: string;
                /** End date for this group */
                end?: string;
                /** Optional accessor identifier */
                accessor?: string;
                /** Optional endpoint identifier */
                endpoint?: string;
                /** Optional feature set identifier */
                feature_set?: string;
                /** Optional models identifier */
                models?: string;
                /** Optional method identifier */
                method?: string;
                /** Optional tags */
                tags?: string;
                /** Optional deployment identifier */
                deployment?: string;
            }
        }
    }
}
