/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../../../../../environments.js";
import * as core from "../../../../../../../../../../../../core/index.js";
import * as Deepgram from "../../../../../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../../../../../errors/index.js";

export declare namespace Purchases {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Purchases {
    protected readonly _options: Purchases.Options;

    constructor(_options: Purchases.Options = {}) {
        this._options = _options;
    }

    /**
     * Returns the original purchased amount on an order transaction
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.billing.PurchasesListRequest} request
     * @param {Purchases.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.billing.purchases.list("123456-7890-1234-5678-901234", {
     *         limit: 1.1
     *     })
     */
    public list(
        projectId: string,
        request: Deepgram.manage.v1.projects.billing.PurchasesListRequest = {},
        requestOptions?: Purchases.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.ListProjectPurchasesV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(projectId, request, requestOptions));
    }

    private async __list(
        projectId: string,
        request: Deepgram.manage.v1.projects.billing.PurchasesListRequest = {},
        requestOptions?: Purchases.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.ListProjectPurchasesV1Response>> {
        const { limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}/purchases`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Deepgram.ListProjectPurchasesV1Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling GET /v1/projects/{project_id}/purchases.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
