// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../../../environments.js";
import * as errors from "../../../../../../../../../../../../errors/index.js";
import * as Deepgram from "../../../../../../../../../../../index.js";

export declare namespace PurchasesClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PurchasesClient {
    protected readonly _options: PurchasesClient.Options;

    constructor(options: PurchasesClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Returns the original purchased amount on an order transaction
     *
     * @param {string} project_id - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.billing.PurchasesListRequest} request
     * @param {PurchasesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.billing.purchases.list("123456-7890-1234-5678-901234", {
     *         limit: 1.1
     *     })
     */
    public list(
        project_id: string,
        request: Deepgram.manage.v1.projects.billing.PurchasesListRequest = {},
        requestOptions?: PurchasesClient.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.ListProjectPurchasesV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(project_id, request, requestOptions));
    }

    private async __list(
        project_id: string,
        request: Deepgram.manage.v1.projects.billing.PurchasesListRequest = {},
        requestOptions?: PurchasesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.ListProjectPurchasesV1Response>> {
        const { limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${core.url.encodePathParam(project_id)}/purchases`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Deepgram.ListProjectPurchasesV1Response,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling GET /v1/projects/{project_id}/purchases.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env.DEEPGRAM_API_KEY;
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
