/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { V1 } from "../resources/v1/client/Client.js";

export declare namespace Speak {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class Speak {
    protected readonly _options: Speak.Options;
    protected _v1: V1 | undefined;

    constructor(_options: Speak.Options = {}) {
        this._options = _options;
    }

    public get v1(): V1 {
        return (this._v1 ??= new V1(this._options));
    }
}
