// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { V1Client } from "../resources/v1/client/Client.js";

export declare namespace AgentClient {
    export type Options = BaseClientOptions;
}

export class AgentClient {
    protected readonly _options: NormalizedClientOptions<AgentClient.Options>;
    protected _v1: V1Client | undefined;

    constructor(options: AgentClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get v1(): V1Client {
        return (this._v1 ??= new V1Client(this._options));
    }
}
