/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../mock-server/MockServerPool";
import { DeepgramClient } from "../../../../src/Client";
import * as Deepgram from "../../../../src/api/index";

describe("Tokens", () => {
    test("grant (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            access_token:
                "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U",
            expires_in: 30,
        };
        server
            .mockEndpoint()
            .post("/v1/auth/grant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.v1.tokens.grant();
        expect(response).toEqual({
            access_token:
                "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U",
            expires_in: 30,
        });
    });

    test("grant (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = { ttl_seconds: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/auth/grant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.v1.tokens.grant({
                ttl_seconds: undefined,
            });
        }).rejects.toThrow(
            new Deepgram.BadRequestError({
                key: "value",
            }),
        );
    });
});
