// This file was auto-generated by Fern from our API Definition.

/** Deployment type for the requests */
export const UsageGetRequestDeployment = {
    Hosted: "hosted",
    Beta: "beta",
    SelfHosted: "self-hosted",
} as const;
export type UsageGetRequestDeployment = (typeof UsageGetRequestDeployment)[keyof typeof UsageGetRequestDeployment];
