// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../../../src/api/index";
import { DeepgramClient } from "../../../../../../src/Client";
import { mockServerPool } from "../../../../../mock-server/MockServerPool";

describe("BreakdownClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            start: "2025-01-16",
            end: "2025-01-23",
            resolution: { units: "day", amount: 1 },
            results: [
                {
                    dollars: 0.25,
                    grouping: {
                        start: "2025-01-16",
                        end: "2025-01-16",
                        accessor: "123456789012345678901234",
                        deployment: "hosted",
                        line_item: "streaming::nova-3",
                        tags: ["tag1", "tag2"],
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/billing/breakdown")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.billing.breakdown.list("123456-7890-1234-5678-901234", {
            start: "start",
            end: "end",
            accessor: "12345678-1234-1234-1234-123456789012",
            deployment: "hosted",
            tag: "tag1",
            line_item: "streaming::nova-3",
        });
        expect(response).toEqual({
            start: "2025-01-16",
            end: "2025-01-23",
            resolution: {
                units: "day",
                amount: 1,
            },
            results: [
                {
                    dollars: 0.25,
                    grouping: {
                        start: "2025-01-16",
                        end: "2025-01-16",
                        accessor: "123456789012345678901234",
                        deployment: "hosted",
                        line_item: "streaming::nova-3",
                        tags: ["tag1", "tag2"],
                    },
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/billing/breakdown")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.billing.breakdown.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
