// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../../../errors/index.js";
import * as Deepgram from "../../../../../../../../../index.js";
import { BreakdownClient } from "../resources/breakdown/client/Client.js";
import { FieldsClient } from "../resources/fields/client/Client.js";

export declare namespace UsageClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class UsageClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<UsageClient.Options>;
    protected _breakdown: BreakdownClient | undefined;
    protected _fields: FieldsClient | undefined;

    constructor(options: UsageClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get breakdown(): BreakdownClient {
        return (this._breakdown ??= new BreakdownClient(this._options));
    }

    public get fields(): FieldsClient {
        return (this._fields ??= new FieldsClient(this._options));
    }

    /**
     * Retrieves the usage for a specific project. Use Get Project Usage Breakdown for a more comprehensive usage summary.
     *
     * @param {string} project_id - The unique identifier of the project
     * @param {Deepgram.manage.v1.projects.UsageGetRequest} request
     * @param {UsageClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.usage.get("123456-7890-1234-5678-901234", {
     *         start: "start",
     *         end: "end",
     *         accessor: "12345678-1234-1234-1234-123456789012",
     *         alternatives: true,
     *         callback_method: true,
     *         callback: true,
     *         channels: true,
     *         custom_intent_mode: true,
     *         custom_intent: true,
     *         custom_topic_mode: true,
     *         custom_topic: true,
     *         deployment: "hosted",
     *         detect_entities: true,
     *         detect_language: true,
     *         diarize: true,
     *         dictation: true,
     *         encoding: true,
     *         endpoint: "listen",
     *         extra: true,
     *         filler_words: true,
     *         intents: true,
     *         keyterm: true,
     *         keywords: true,
     *         language: true,
     *         measurements: true,
     *         method: "sync",
     *         model: "6f548761-c9c0-429a-9315-11a1d28499c8",
     *         multichannel: true,
     *         numerals: true,
     *         paragraphs: true,
     *         profanity_filter: true,
     *         punctuate: true,
     *         redact: true,
     *         replace: true,
     *         sample_rate: true,
     *         search: true,
     *         sentiment: true,
     *         smart_format: true,
     *         summarize: true,
     *         tag: "tag1",
     *         topics: true,
     *         utt_split: true,
     *         utterances: true,
     *         version: true
     *     })
     */
    public get(
        project_id: string,
        request: Deepgram.manage.v1.projects.UsageGetRequest = {},
        requestOptions?: UsageClient.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.UsageV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__get(project_id, request, requestOptions));
    }

    private async __get(
        project_id: string,
        request: Deepgram.manage.v1.projects.UsageGetRequest = {},
        requestOptions?: UsageClient.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.UsageV1Response>> {
        const {
            start,
            end,
            accessor,
            alternatives,
            callback_method: callbackMethod,
            callback,
            channels,
            custom_intent_mode: customIntentMode,
            custom_intent: customIntent,
            custom_topic_mode: customTopicMode,
            custom_topic: customTopic,
            deployment,
            detect_entities: detectEntities,
            detect_language: detectLanguage,
            diarize,
            dictation,
            encoding,
            endpoint,
            extra,
            filler_words: fillerWords,
            intents,
            keyterm,
            keywords,
            language,
            measurements,
            method,
            model,
            multichannel,
            numerals,
            paragraphs,
            profanity_filter: profanityFilter,
            punctuate,
            redact,
            replace,
            sample_rate: sampleRate,
            search,
            sentiment,
            smart_format: smartFormat,
            summarize,
            tag,
            topics,
            utt_split: uttSplit,
            utterances,
            version,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (start != null) {
            _queryParams.start = start;
        }

        if (end != null) {
            _queryParams.end = end;
        }

        if (accessor != null) {
            _queryParams.accessor = accessor;
        }

        if (alternatives != null) {
            _queryParams.alternatives = alternatives.toString();
        }

        if (callbackMethod != null) {
            _queryParams.callback_method = callbackMethod.toString();
        }

        if (callback != null) {
            _queryParams.callback = callback.toString();
        }

        if (channels != null) {
            _queryParams.channels = channels.toString();
        }

        if (customIntentMode != null) {
            _queryParams.custom_intent_mode = customIntentMode.toString();
        }

        if (customIntent != null) {
            _queryParams.custom_intent = customIntent.toString();
        }

        if (customTopicMode != null) {
            _queryParams.custom_topic_mode = customTopicMode.toString();
        }

        if (customTopic != null) {
            _queryParams.custom_topic = customTopic.toString();
        }

        if (deployment != null) {
            _queryParams.deployment = deployment;
        }

        if (detectEntities != null) {
            _queryParams.detect_entities = detectEntities.toString();
        }

        if (detectLanguage != null) {
            _queryParams.detect_language = detectLanguage.toString();
        }

        if (diarize != null) {
            _queryParams.diarize = diarize.toString();
        }

        if (dictation != null) {
            _queryParams.dictation = dictation.toString();
        }

        if (encoding != null) {
            _queryParams.encoding = encoding.toString();
        }

        if (endpoint != null) {
            _queryParams.endpoint = endpoint;
        }

        if (extra != null) {
            _queryParams.extra = extra.toString();
        }

        if (fillerWords != null) {
            _queryParams.filler_words = fillerWords.toString();
        }

        if (intents != null) {
            _queryParams.intents = intents.toString();
        }

        if (keyterm != null) {
            _queryParams.keyterm = keyterm.toString();
        }

        if (keywords != null) {
            _queryParams.keywords = keywords.toString();
        }

        if (language != null) {
            _queryParams.language = language.toString();
        }

        if (measurements != null) {
            _queryParams.measurements = measurements.toString();
        }

        if (method != null) {
            _queryParams.method = method;
        }

        if (model != null) {
            _queryParams.model = model;
        }

        if (multichannel != null) {
            _queryParams.multichannel = multichannel.toString();
        }

        if (numerals != null) {
            _queryParams.numerals = numerals.toString();
        }

        if (paragraphs != null) {
            _queryParams.paragraphs = paragraphs.toString();
        }

        if (profanityFilter != null) {
            _queryParams.profanity_filter = profanityFilter.toString();
        }

        if (punctuate != null) {
            _queryParams.punctuate = punctuate.toString();
        }

        if (redact != null) {
            _queryParams.redact = redact.toString();
        }

        if (replace != null) {
            _queryParams.replace = replace.toString();
        }

        if (sampleRate != null) {
            _queryParams.sample_rate = sampleRate.toString();
        }

        if (search != null) {
            _queryParams.search = search.toString();
        }

        if (sentiment != null) {
            _queryParams.sentiment = sentiment.toString();
        }

        if (smartFormat != null) {
            _queryParams.smart_format = smartFormat.toString();
        }

        if (summarize != null) {
            _queryParams.summarize = summarize.toString();
        }

        if (tag != null) {
            _queryParams.tag = tag;
        }

        if (topics != null) {
            _queryParams.topics = topics.toString();
        }

        if (uttSplit != null) {
            _queryParams.utt_split = uttSplit.toString();
        }

        if (utterances != null) {
            _queryParams.utterances = utterances.toString();
        }

        if (version != null) {
            _queryParams.version = version.toString();
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${core.url.encodePathParam(project_id)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.UsageV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{project_id}/usage",
        );
    }
}
