/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../../mock-server/MockServerPool";
import { DeepgramClient } from "../../../../../src/Client";
import * as Deepgram from "../../../../../src/api/index";

describe("Members", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { members: [{ member_id: "member_id", email: "email" }] };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/members")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.members.list("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            members: [
                {
                    member_id: "member_id",
                    email: "email",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/members")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.members.list("project_id");
        }).rejects.toThrow(
            new Deepgram.BadRequestError({
                key: "value",
            }),
        );
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/v1/projects/123456-7890-1234-5678-901234/members/123456789012345678901234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.members.delete(
            "123456-7890-1234-5678-901234",
            "123456789012345678901234",
        );
        expect(response).toEqual({
            message: "message",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/projects/project_id/members/member_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.members.delete("project_id", "member_id");
        }).rejects.toThrow(
            new Deepgram.BadRequestError({
                key: "value",
            }),
        );
    });
});
