// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../../src/api/index";
import { DeepgramClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("RequestsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: {
                base: server.baseUrl,
                production: server.baseUrl,
                agent: server.baseUrl,
                agentRest: server.baseUrl,
            },
        });

        const rawResponseBody = {
            page: 0,
            limit: 10,
            requests: [
                {
                    request_id: "a3f1c9d2-4b7e-4f9a-8c3d-2e5f7b9a1c0d",
                    project_uuid: "12345678-90ab-cdef-1234-567890abcdef",
                    created: "2024-01-15T09:48:20.000Z",
                    path: "/v1/listen?",
                    api_key_id: "b1e2c3d4-5678-90ab-cdef-1234567890ab",
                    response: {
                        details: {
                            usd: 0.0075,
                            duration: 30,
                            total_audio: 30,
                            channels: 1,
                            streams: 1,
                            tier: "base",
                            metadata: {},
                            models: ["1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d"],
                            method: "sync",
                            tags: [],
                            features: [],
                            config: {},
                        },
                        token_details: [],
                        code: 200,
                        completed: "2024-01-15T09:48:21.000Z",
                        deployment: "hosted:us",
                    },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/projects/12345678-90ab-cdef-1234-567890abcdef/requests")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.requests.list("12345678-90ab-cdef-1234-567890abcdef");
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: {
                base: server.baseUrl,
                production: server.baseUrl,
                agent: server.baseUrl,
                agentRest: server.baseUrl,
            },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/projects/project_id/requests")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.requests.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: {
                base: server.baseUrl,
                production: server.baseUrl,
                agent: server.baseUrl,
                agentRest: server.baseUrl,
            },
        });

        const rawResponseBody = {
            request: {
                request_id: "a3f1c9d2-4b7e-4f9a-8c3d-2e5f7b9a1c0d",
                project_uuid: "12345678-90ab-cdef-1234-567890abcdef",
                created: "2024-01-15T09:48:20.000Z",
                path: "/v1/listen?",
                api_key_id: "b1e2c3d4-5678-90ab-cdef-1234567890ab",
                response: {
                    details: {
                        usd: 0.0075,
                        duration: 30,
                        total_audio: 30,
                        channels: 1,
                        streams: 1,
                        tier: "base",
                        metadata: {},
                        models: ["1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d"],
                        method: "sync",
                        tags: [],
                        features: [],
                        config: {},
                    },
                    token_details: [],
                    code: 200,
                    completed: "2024-01-15T09:48:21.000Z",
                    deployment: "hosted:us",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/v1/projects/12345678-90ab-cdef-1234-567890abcdef/requests/a3f1c9d2-4b7e-4f9a-8c3d-2e5f7b9a1c0d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.requests.get(
            "12345678-90ab-cdef-1234-567890abcdef",
            "a3f1c9d2-4b7e-4f9a-8c3d-2e5f7b9a1c0d",
        );
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: {
                base: server.baseUrl,
                production: server.baseUrl,
                agent: server.baseUrl,
                agentRest: server.baseUrl,
            },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/projects/project_id/requests/request_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.requests.get("project_id", "request_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
