// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../../src/api/index";
import { DeepgramClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("RequestsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = {
            page: 1.1,
            limit: 1.1,
            requests: [
                {
                    request_id: "request_id",
                    project_uuid: "project_uuid",
                    created: "2024-01-15T09:30:00Z",
                    path: "path",
                    api_key_id: "api_key_id",
                    response: { key: "value" },
                    code: 1.1,
                    deployment: "deployment",
                    callback: "callback",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/requests")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.requests.list("123456-7890-1234-5678-901234", {
            start: "2024-01-15T09:30:00Z",
            end: "2024-01-15T09:30:00Z",
            limit: 1.1,
            page: 1.1,
            accessor: "12345678-1234-1234-1234-123456789012",
            request_id: "12345678-1234-1234-1234-123456789012",
            deployment: "hosted",
            endpoint: "listen",
            method: "sync",
            status: "succeeded",
        });
        expect(response).toEqual({
            page: 1.1,
            limit: 1.1,
            requests: [
                {
                    request_id: "request_id",
                    project_uuid: "project_uuid",
                    created: "2024-01-15T09:30:00Z",
                    path: "path",
                    api_key_id: "api_key_id",
                    response: {
                        key: "value",
                    },
                    code: 1.1,
                    deployment: "deployment",
                    callback: "callback",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/requests")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.requests.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = {
            request: {
                request_id: "request_id",
                project_uuid: "project_uuid",
                created: "2024-01-15T09:30:00Z",
                path: "path",
                api_key_id: "api_key_id",
                response: { key: "value" },
                code: 1.1,
                deployment: "deployment",
                callback: "callback",
            },
        };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/requests/123456-7890-1234-5678-901234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.requests.get(
            "123456-7890-1234-5678-901234",
            "123456-7890-1234-5678-901234",
        );
        expect(response).toEqual({
            request: {
                request_id: "request_id",
                project_uuid: "project_uuid",
                created: "2024-01-15T09:30:00Z",
                path: "path",
                api_key_id: "api_key_id",
                response: {
                    key: "value",
                },
                code: 1.1,
                deployment: "deployment",
                callback: "callback",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/requests/request_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.requests.get("project_id", "request_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
