// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../../src/api/index";
import { DeepgramClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("UsageClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { start: "2024-10-16", end: "2024-10-23", resolution: { units: "day", amount: 1 } };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/usage")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.usage.get("123456-7890-1234-5678-901234", {
            start: "start",
            end: "end",
            accessor: "12345678-1234-1234-1234-123456789012",
            alternatives: true,
            callback_method: true,
            callback: true,
            channels: true,
            custom_intent_mode: true,
            custom_intent: true,
            custom_topic_mode: true,
            custom_topic: true,
            deployment: "hosted",
            detect_entities: true,
            detect_language: true,
            diarize: true,
            dictation: true,
            encoding: true,
            endpoint: "listen",
            extra: true,
            filler_words: true,
            intents: true,
            keyterm: true,
            keywords: true,
            language: true,
            measurements: true,
            method: "sync",
            model: "6f548761-c9c0-429a-9315-11a1d28499c8",
            multichannel: true,
            numerals: true,
            paragraphs: true,
            profanity_filter: true,
            punctuate: true,
            redact: true,
            replace: true,
            sample_rate: true,
            search: true,
            sentiment: true,
            smart_format: true,
            summarize: true,
            tag: "tag1",
            topics: true,
            utt_split: true,
            utterances: true,
            version: true,
        });
        expect(response).toEqual({
            start: "2024-10-16",
            end: "2024-10-23",
            resolution: {
                units: "day",
                amount: 1,
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/usage")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.usage.get("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
