/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         scope: "admin"
 *     }
 */
export interface UpdateProjectMemberScopesV1Request {
    /** A scope to update */
    scope: string;
}
