/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../../../environments.js";
import * as core from "../../../../../../../../../../core/index.js";
import { Models } from "../resources/models/client/Client.js";

export declare namespace Think {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class Think {
    protected readonly _options: Think.Options;
    protected _models: Models | undefined;

    constructor(_options: Think.Options = {}) {
        this._options = _options;
    }

    public get models(): Models {
        return (this._models ??= new Models(this._options));
    }
}
