/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as Deepgram from "../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../errors/index.js";

export declare namespace Audio {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Audio {
    protected readonly _options: Audio.Options;

    constructor(_options: Audio.Options = {}) {
        this._options = _options;
    }

    /**
     * Convert text into natural-sounding speech using Deepgram's TTS REST API
     * @throws {@link Deepgram.BadRequestError}
     */
    public generate(
        request: Deepgram.speak.v1.SpeakV1Request,
        requestOptions?: Audio.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__generate(request, requestOptions));
    }

    private async __generate(
        request: Deepgram.speak.v1.SpeakV1Request,
        requestOptions?: Audio.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const {
            callback,
            callback_method: callbackMethod,
            mip_opt_out: mipOptOut,
            tag,
            bit_rate: bitRate,
            container,
            encoding,
            model,
            sample_rate: sampleRate,
            ..._body
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (callback != null) {
            _queryParams["callback"] = callback;
        }

        if (callbackMethod != null) {
            _queryParams["callback_method"] = callbackMethod;
        }

        if (mipOptOut != null) {
            _queryParams["mip_opt_out"] = mipOptOut.toString();
        }

        if (tag != null) {
            if (Array.isArray(tag)) {
                _queryParams["tag"] = tag.map((item) => item);
            } else {
                _queryParams["tag"] = tag;
            }
        }

        if (bitRate != null) {
            _queryParams["bit_rate"] = bitRate.toString();
        }

        if (container != null) {
            _queryParams["container"] = container;
        }

        if (encoding != null) {
            _queryParams["encoding"] = encoding;
        }

        if (model != null) {
            _queryParams["model"] = model;
        }

        if (sampleRate != null) {
            _queryParams["sample_rate"] = sampleRate.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                "v1/speak",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            responseType: "binary-response",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling POST /v1/speak.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
