// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         config: "config"
 *     }
 */
export interface CreateAgentConfigurationV1Request {
    /** A valid JSON string representing the agent block of a Settings message */
    config: string;
    /** A map of arbitrary key-value pairs for labeling or organizing the agent configuration */
    metadata?: Record<string, string>;
    /** API version. Defaults to 1 */
    api_version?: number;
}
