// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         metadata: {
 *             "key": "value"
 *         }
 *     }
 */
export interface UpdateAgentMetadataV1Request {
    /** A map of string key-value pairs to associate with this agent configuration */
    metadata: Record<string, string>;
}
