// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../BaseClient.js";
import { TokensClient } from "../resources/tokens/client/Client.js";

export declare namespace V1Client {
    export interface Options extends BaseClientOptions {}
}

export class V1Client {
    protected readonly _options: V1Client.Options;
    protected _tokens: TokensClient | undefined;

    constructor(options: V1Client.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get tokens(): TokensClient {
        return (this._tokens ??= new TokensClient(this._options));
    }
}
