/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../../mock-server/MockServerPool";
import { DeepgramClient } from "../../../../src/Client";
import * as Deepgram from "../../../../src/api/index";

describe("Media", () => {
    test("transcribeUrl (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = { url: "https://dpgr.am/spacewalk.wav" };
        const rawResponseBody = {
            metadata: {
                request_id: "a847f427-4ad5-4d67-9b95-db801e58251c",
                sha256: "154e291ecfa8be6ab8343560bcc109008fa7853eb5372533e8efdefc9b504c33",
                created: "2024-05-12T18:57:13Z",
                duration: 25.933313,
                channels: 1,
                models: ["30089e05-99d1-4376-b32e-c263170674af"],
                model_info: {
                    "30089e05-99d1-4376-b32e-c263170674af": {
                        name: "2-general-nova",
                        version: "2024-01-09.29447",
                        arch: "nova-2",
                    },
                },
                summary_info: {
                    model_uuid: "67875a7f-c9c4-48a0-aa55-5bdb8a91c34a",
                    input_tokens: 95,
                    output_tokens: 63,
                },
                sentiment_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 105,
                },
                topics_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 7,
                },
                intents_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 4,
                },
                tags: ["test"],
            },
            results: {
                channels: [{}],
                utterances: [{}],
                summary: {
                    result: "success",
                    short: "Speaker 0 discusses the significance of the first all-female spacewalk with an all-female team, stating that it is a tribute to the skilled and qualified women who were denied opportunities in the past.",
                },
                sentiments: {
                    segments: [
                        {
                            text: "Yeah. As as much as, um, it's worth celebrating, uh, the first, uh, spacewalk, um, with an all-female team, I think many of us are looking forward to it just being normal. And, um, I think if it signifies anything, it is, uh, to honor the the women who came before us who, um, were skilled and qualified, um, and didn't get the the same opportunities that we have today.",
                            start_word: 0,
                            end_word: 69,
                            sentiment: "positive",
                            sentiment_score: 0.5810546875,
                        },
                    ],
                    average: { sentiment: "positive", sentiment_score: 0.5810185185185185 },
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v1/listen")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.listen.v1.media.transcribeUrl({
            callback: "callback",
            callback_method: "POST",
            extra: "extra",
            sentiment: true,
            summarize: "v2",
            tag: "tag",
            topics: true,
            custom_topic: "custom_topic",
            custom_topic_mode: "extended",
            intents: true,
            custom_intent: "custom_intent",
            custom_intent_mode: "extended",
            detect_entities: true,
            detect_language: true,
            diarize: true,
            dictation: true,
            encoding: "linear16",
            filler_words: true,
            keywords: "keywords",
            language: "language",
            measurements: true,
            model: "nova-3",
            multichannel: true,
            numerals: true,
            paragraphs: true,
            profanity_filter: true,
            punctuate: true,
            redact: "redact",
            replace: "replace",
            search: "search",
            smart_format: true,
            utterances: true,
            utt_split: 1.1,
            version: "latest",
            mip_opt_out: true,
            url: "https://dpgr.am/spacewalk.wav",
        });
        expect(response).toEqual({
            metadata: {
                request_id: "a847f427-4ad5-4d67-9b95-db801e58251c",
                sha256: "154e291ecfa8be6ab8343560bcc109008fa7853eb5372533e8efdefc9b504c33",
                created: "2024-05-12T18:57:13Z",
                duration: 25.933313,
                channels: 1,
                models: ["30089e05-99d1-4376-b32e-c263170674af"],
                model_info: {
                    "30089e05-99d1-4376-b32e-c263170674af": {
                        name: "2-general-nova",
                        version: "2024-01-09.29447",
                        arch: "nova-2",
                    },
                },
                summary_info: {
                    model_uuid: "67875a7f-c9c4-48a0-aa55-5bdb8a91c34a",
                    input_tokens: 95,
                    output_tokens: 63,
                },
                sentiment_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 105,
                },
                topics_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 7,
                },
                intents_info: {
                    model_uuid: "80ab3179-d113-4254-bd6b-4a2f96498695",
                    input_tokens: 105,
                    output_tokens: 4,
                },
                tags: ["test"],
            },
            results: {
                channels: [{}],
                utterances: [{}],
                summary: {
                    result: "success",
                    short: "Speaker 0 discusses the significance of the first all-female spacewalk with an all-female team, stating that it is a tribute to the skilled and qualified women who were denied opportunities in the past.",
                },
                sentiments: {
                    segments: [
                        {
                            text: "Yeah. As as much as, um, it's worth celebrating, uh, the first, uh, spacewalk, um, with an all-female team, I think many of us are looking forward to it just being normal. And, um, I think if it signifies anything, it is, uh, to honor the the women who came before us who, um, were skilled and qualified, um, and didn't get the the same opportunities that we have today.",
                            start_word: 0,
                            end_word: 69,
                            sentiment: "positive",
                            sentiment_score: 0.5810546875,
                        },
                    ],
                    average: {
                        sentiment: "positive",
                        sentiment_score: 0.5810185185185185,
                    },
                },
            },
        });
    });

    test("transcribeUrl (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/listen")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.listen.v1.media.transcribeUrl({
                url: "url",
            });
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
