// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { MediaClient } from "../resources/media/client/Client.js";

export declare namespace V1Client {
    export type Options = BaseClientOptions;
}

export class V1Client {
    protected readonly _options: NormalizedClientOptionsWithAuth<V1Client.Options>;
    protected _media: MediaClient | undefined;

    constructor(options: V1Client.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get media(): MediaClient {
        return (this._media ??= new MediaClient(this._options));
    }
}
