/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments.js";
import * as core from "../../../../../../core/index.js";
import { mergeOnlyDefinedHeaders, mergeHeaders } from "../../../../../../core/headers.js";
import { V1Socket } from "./Socket.js";
import { Media } from "../resources/media/client/Client.js";

export declare namespace V1 {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface ConnectArgs {
        callback?: string | undefined;
        callback_method?: string | undefined;
        channels?: string | undefined;
        diarize?: string | undefined;
        dictation?: string | undefined;
        encoding?: string | undefined;
        endpointing?: string | undefined;
        extra?: string | undefined;
        interim_results?: string | undefined;
        keyterm?: string | undefined;
        keywords?: string | undefined;
        language?: string | undefined;
        mip_opt_out?: string | undefined;
        model: string;
        multichannel?: string | undefined;
        numerals?: string | undefined;
        profanity_filter?: string | undefined;
        punctuate?: string | undefined;
        redact?: string | undefined;
        replace?: string | undefined;
        sample_rate?: string | undefined;
        search?: string | undefined;
        smart_format?: string | undefined;
        tag?: string | undefined;
        utterance_end_ms?: string | undefined;
        vad_events?: string | undefined;
        version?: string | undefined;
        Authorization: string;
        /** Arbitrary headers to send with the websocket connect request. */
        headers?: Record<string, string>;
        /** Enable debug mode on the websocket. Defaults to false. */
        debug?: boolean;
        /** Number of reconnect attempts. Defaults to 30. */
        reconnectAttempts?: number;
    }
}

export class V1 {
    protected readonly _options: V1.Options;
    protected _media: Media | undefined;

    constructor(_options: V1.Options = {}) {
        this._options = _options;
    }

    public get media(): Media {
        return (this._media ??= new Media(this._options));
    }

    public async connect(args: V1.ConnectArgs): Promise<V1Socket> {
        const {
            callback,
            callback_method,
            channels,
            diarize,
            dictation,
            encoding,
            endpointing,
            extra,
            interim_results,
            keyterm,
            keywords,
            language,
            mip_opt_out,
            model,
            multichannel,
            numerals,
            profanity_filter,
            punctuate,
            redact,
            replace,
            sample_rate,
            search,
            smart_format,
            tag,
            utterance_end_ms,
            vad_events,
            version,
            headers,
            debug,
            reconnectAttempts,
        } = args;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (callback != null) {
            _queryParams["callback"] = callback;
        }

        if (callback_method != null) {
            _queryParams["callback_method"] = callback_method;
        }

        if (channels != null) {
            _queryParams["channels"] = channels;
        }

        if (diarize != null) {
            _queryParams["diarize"] = diarize;
        }

        if (dictation != null) {
            _queryParams["dictation"] = dictation;
        }

        if (encoding != null) {
            _queryParams["encoding"] = encoding;
        }

        if (endpointing != null) {
            _queryParams["endpointing"] = endpointing;
        }

        if (extra != null) {
            _queryParams["extra"] = extra;
        }

        if (interim_results != null) {
            _queryParams["interim_results"] = interim_results;
        }

        if (keyterm != null) {
            _queryParams["keyterm"] = keyterm;
        }

        if (keywords != null) {
            _queryParams["keywords"] = keywords;
        }

        if (language != null) {
            _queryParams["language"] = language;
        }

        if (mip_opt_out != null) {
            _queryParams["mip_opt_out"] = mip_opt_out;
        }

        _queryParams["model"] = model;
        if (multichannel != null) {
            _queryParams["multichannel"] = multichannel;
        }

        if (numerals != null) {
            _queryParams["numerals"] = numerals;
        }

        if (profanity_filter != null) {
            _queryParams["profanity_filter"] = profanity_filter;
        }

        if (punctuate != null) {
            _queryParams["punctuate"] = punctuate;
        }

        if (redact != null) {
            _queryParams["redact"] = redact;
        }

        if (replace != null) {
            _queryParams["replace"] = replace;
        }

        if (sample_rate != null) {
            _queryParams["sample_rate"] = sample_rate;
        }

        if (search != null) {
            _queryParams["search"] = search;
        }

        if (smart_format != null) {
            _queryParams["smart_format"] = smart_format;
        }

        if (tag != null) {
            _queryParams["tag"] = tag;
        }

        if (utterance_end_ms != null) {
            _queryParams["utterance_end_ms"] = utterance_end_ms;
        }

        if (vad_events != null) {
            _queryParams["vad_events"] = vad_events;
        }

        if (version != null) {
            _queryParams["version"] = version;
        }

        let _headers: Record<string, unknown> = mergeHeaders(
            mergeOnlyDefinedHeaders({
                ...(await this._getCustomAuthorizationHeaders()),
                Authorization: args["Authorization"],
            }),
            headers,
        );
        const socket = new core.ReconnectingWebSocket({
            url: core.url.join(
                (await core.Supplier.get(this._options["baseUrl"])) ??
                    (
                        (await core.Supplier.get(this._options["environment"])) ??
                        environments.DeepgramEnvironment.Production
                    ).production,
                "/v1/listen",
            ),
            protocols: [],
            queryParameters: _queryParams,
            headers: _headers,
            options: { debug: debug ?? false, maxRetries: reconnectAttempts ?? 30 },
        });
        return new V1Socket({ socket });
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
