// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../src/api/index";
import { DeepgramClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("TextClient", () => {
    test("analyze (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = {
            metadata: {
                metadata: {
                    request_id: "d04af392-db11-4c1d-83e1-20e34f0b8999",
                    created: "2024-11-18T23:47:44Z",
                    language: "en",
                },
            },
            results: {
                sentiments: {
                    segments: [
                        {
                            text: "Yeah. As as much as, um, it's worth celebrating, uh, the first, uh, spacewalk, um, with an all-female team, I think many of us are looking forward to it just being normal. And, um, I think if it signifies anything, it is, uh, to honor the the women who came before us who, um, were skilled and qualified, um, and didn't get the the same opportunities that we have today.",
                            start_word: 0,
                            end_word: 69,
                            sentiment: "positive",
                            sentiment_score: 0.5810546875,
                        },
                    ],
                    average: { sentiment: "positive", sentiment_score: 0.5810185185185185 },
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v1/read")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.read.v1.text.analyze({
            callback: "callback",
            callback_method: "POST",
            sentiment: true,
            summarize: "v2",
            tag: "tag",
            topics: true,
            custom_topic: "custom_topic",
            custom_topic_mode: "extended",
            intents: true,
            custom_intent: "custom_intent",
            custom_intent_mode: "extended",
            language: "language",
            body: {
                url: "url",
            },
        });
        expect(response).toEqual({
            metadata: {
                metadata: {
                    request_id: "d04af392-db11-4c1d-83e1-20e34f0b8999",
                    created: "2024-11-18T23:47:44Z",
                    language: "en",
                },
            },
            results: {
                sentiments: {
                    segments: [
                        {
                            text: "Yeah. As as much as, um, it's worth celebrating, uh, the first, uh, spacewalk, um, with an all-female team, I think many of us are looking forward to it just being normal. And, um, I think if it signifies anything, it is, uh, to honor the the women who came before us who, um, were skilled and qualified, um, and didn't get the the same opportunities that we have today.",
                            start_word: 0,
                            end_word: 69,
                            sentiment: "positive",
                            sentiment_score: 0.5810546875,
                        },
                    ],
                    average: {
                        sentiment: "positive",
                        sentiment_score: 0.5810185185185185,
                    },
                },
            },
        });
    });

    test("analyze (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, agent: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/read")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.read.v1.text.analyze({
                body: {
                    url: "url",
                },
            });
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
