/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AudioGenerateRequestContainer = "none" | "wav" | "ogg";
export const AudioGenerateRequestContainer = {
    None: "none",
    Wav: "wav",
    Ogg: "ogg",
} as const;
