// This file was auto-generated by Fern from our API Definition.

export const AudioGenerateRequestEncoding = {
    Linear16: "linear16",
    Flac: "flac",
    Mulaw: "mulaw",
    Alaw: "alaw",
    Mp3: "mp3",
    Opus: "opus",
    Aac: "aac",
} as const;
export type AudioGenerateRequestEncoding =
    (typeof AudioGenerateRequestEncoding)[keyof typeof AudioGenerateRequestEncoding];
