/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AudioGenerateRequestEncoding = "linear16" | "flac" | "mulaw" | "alaw" | "mp3" | "opus" | "aac";
export const AudioGenerateRequestEncoding = {
    Linear16: "linear16",
    Flac: "flac",
    Mulaw: "mulaw",
    Alaw: "alaw",
    Mp3: "mp3",
    Opus: "opus",
    Aac: "aac",
} as const;
