// This file was auto-generated by Fern from our API Definition.

export const AudioGenerateRequestContainer = {
    None: "none",
    Wav: "wav",
    Ogg: "ogg",
} as const;
export type AudioGenerateRequestContainer =
    | (typeof AudioGenerateRequestContainer)[keyof typeof AudioGenerateRequestContainer]
    | string;
