/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AudioGenerateRequestCallbackMethod = "POST" | "PUT";
export const AudioGenerateRequestCallbackMethod = {
    Post: "POST",
    Put: "PUT",
} as const;
