// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         text: "text"
 *     }
 */
export interface SpeakV2Request {
    /** URL to which we'll make the callback request */
    callback?: string;
    /** HTTP method by which the callback request will be made */
    callback_method?: Deepgram.speak.v2.AudioGenerateRequestCallbackMethod;
    /** Opts out requests from the Deepgram Model Improvement Program. Refer to our Docs for pricing impacts before setting this to true. https://dpgr.am/deepgram-mip */
    mip_opt_out?: boolean;
    /** Label your requests for the purpose of identification during usage reporting */
    tag?: string | string[];
    /** The bitrate of the audio in bits per second. Choose from predefined ranges or specific values based on the encoding type. */
    bit_rate?: number;
    /** Container specifies the file format wrapper for the output audio. The available options depend on the encoding type. */
    container?: Deepgram.speak.v2.AudioGenerateRequestContainer;
    /** Encoding allows you to specify the expected encoding of your audio output */
    encoding?: Deepgram.speak.v2.AudioGenerateRequestEncoding;
    /** Expressive range of the generated speech, on a calm-to-animated axis. Accepted values: `-2`, `-1`, `0`, `1`, `2`. `0` (the default) is the voice's tuned delivery and the production-validated setting, with `-2` the calm end of the range and `2` the animated end. Supported on all Flux voices; applies to the whole request. Beta: behavior may change in future model versions, and non-default values increase the risk of hallucinations and pronunciation errors; audition before shipping. An invalid value is rejected with a `400` — `EXPRESSIVITY_OUT_OF_RANGE` for a value outside the range, `EXPRESSIVITY_INCREMENT_INVALID` for a fractional value. See [Expressivity](/docs/tts-expressivity). */
    expressivity?: number;
    /** Flux TTS model used to synthesize the submitted text, in the form `flux-{voice}-{language}` (for example, `flux-alexis-en`). Required; unlike the v1 (Aura) endpoint there is no default and only flux models are accepted. English-only at launch. */
    model: string;
    /** Sample Rate specifies the sample rate for the output audio. Based on the encoding, different sample rates are supported. For some encodings, the sample rate is not configurable */
    sample_rate?: number;
    /** Speaking rate multiplier that adjusts the pace of generated speech while preserving natural prosody and voice quality. Accepted values run `0.85` to `1.15` in `0.05` increments. Not yet supported in all languages. */
    speed?: number;
    /** Processing priority for asynchronous (callback) requests. The only supported value is low. */
    priority?: "low";
    /** The text content to be converted to speech. The server normalizes and preprocesses the text before synthesis. Inline pause and pronunciation controls are not yet applied; they are stripped from the text before synthesis. */
    text: string;
}
