// This file was auto-generated by Fern from our API Definition.

export interface AgentV1CustomToThinkProvider {
    /** Experimental. Requires a wss:// custom Think endpoint in agent.think.endpoint.url. */
    /** Message type identifier for sending a custom payload to the think provider */
    type: "__customToThinkProvider";
    content: unknown;
}
