// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface AgentV1UpdateThink {
    /** Message type identifier for updating the think model */
    type: "UpdateThink";
    think: AgentV1UpdateThink.Think;
}

export namespace AgentV1UpdateThink {
    export type Think = Deepgram.ThinkSettingsV1 | Deepgram.ThinkSettingsV1[];
}
