// This file was auto-generated by Fern from our API Definition.

export interface AgentV1FunctionCallCancelled {
    /** Message type identifier for cancelled function calls */
    type: "FunctionCallCancelled";
    /** The function calls that are no longer valid */
    functions: AgentV1FunctionCallCancelled.Functions.Item[];
}

export namespace AgentV1FunctionCallCancelled {
    export type Functions = Functions.Item[];

    export namespace Functions {
        export interface Item {
            /** The id from the FunctionCallRequest that is now cancelled. Send no FunctionCallResponse for this id */
            id: string;
            /** The name of the cancelled function */
            name: string;
        }
    }
}
