/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentV1InjectionRefused {
    /** Message type identifier for injection refused */
    type: "InjectionRefused";
    /** Details about why the injection was refused */
    message: string;
}
