/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentV1FunctionCallRequest {
    /** Message type identifier for function call requests */
    type: "FunctionCallRequest";
    /** Array of functions to be called */
    functions: AgentV1FunctionCallRequest.Functions.Item[];
}

export namespace AgentV1FunctionCallRequest {
    export type Functions = Functions.Item[];

    export namespace Functions {
        export interface Item {
            /** Unique identifier for the function call */
            id: string;
            /** The name of the function to call */
            name: string;
            /** JSON string containing the function arguments */
            arguments: string;
            /** Whether the function should be executed client-side */
            client_side: boolean;
        }
    }
}
