// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export type AgentV1UpdateListenListenProvider =
    | Deepgram.agent.AgentV1UpdateListenListenProvider.V1
    | Deepgram.agent.AgentV1UpdateListenListenProvider.V2;

export namespace AgentV1UpdateListenListenProvider {
    export interface V1 extends Deepgram.DeepgramListenProviderV1 {
        version: "v1";
    }

    export interface V2 extends Deepgram.DeepgramListenProviderV2 {
        version: "v2";
    }
}
