/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Send a control message to the agent
 */
export interface AgentV1KeepAlive {
    /** Message type identifier */
    type: "KeepAlive";
}
