// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface AgentV1Settings {
    type: "Settings";
    /** Tags to associate with the request */
    tags?: string[] | undefined;
    /** To enable experimental features */
    experimental?: boolean | undefined;
    flags?: AgentV1Settings.Flags | undefined;
    /** To opt out of Deepgram Model Improvement Program */
    mip_opt_out?: boolean | undefined;
    audio: AgentV1Settings.Audio;
    agent: AgentV1Settings.Agent;
}

export namespace AgentV1Settings {
    export interface Flags {
        /** Enable or disable history message reporting */
        history?: boolean | undefined;
    }

    export interface Audio {
        /** Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality. */
        input?: Audio.Input | undefined;
        /** Audio output configuration settings */
        output?: Audio.Output | undefined;
    }

    export namespace Audio {
        /**
         * Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality.
         */
        export interface Input {
            /** Audio encoding format */
            encoding: Input.Encoding;
            /** Sample rate in Hz. Common values are 16000, 24000, 44100, 48000 */
            sample_rate: number;
        }

        export namespace Input {
            /** Audio encoding format */
            export const Encoding = {
                Linear16: "linear16",
                Linear32: "linear32",
                Flac: "flac",
                Alaw: "alaw",
                Mulaw: "mulaw",
                AmrNb: "amr-nb",
                AmrWb: "amr-wb",
                Opus: "opus",
                OggOpus: "ogg-opus",
                Speex: "speex",
                G729: "g729",
            } as const;
            export type Encoding = (typeof Encoding)[keyof typeof Encoding] | string;
        }

        /**
         * Audio output configuration settings
         */
        export interface Output {
            /** Audio encoding format for streaming TTS output */
            encoding?: Output.Encoding | undefined;
            /** Sample rate in Hz */
            sample_rate?: number | undefined;
            /** Audio bitrate in bits per second */
            bitrate?: number | undefined;
            /** Audio container format. If omitted, defaults to 'none' */
            container?: string | undefined;
        }

        export namespace Output {
            /** Audio encoding format for streaming TTS output */
            export const Encoding = {
                Linear16: "linear16",
                Mulaw: "mulaw",
                Alaw: "alaw",
            } as const;
            export type Encoding = (typeof Encoding)[keyof typeof Encoding] | string;
        }
    }

    export interface Agent {
        /** Deprecated. Use `listen.provider.language` and `speak.provider.language` fields instead. */
        language?: string | undefined;
        /** Conversation context including the history of messages and function calls */
        context?: Agent.Context | undefined;
        listen?: Agent.Listen | undefined;
        think?: Agent.Think | undefined;
        speak?: Agent.Speak | undefined;
        /** Optional message that agent will speak at the start */
        greeting?: string | undefined;
    }

    export namespace Agent {
        /**
         * Conversation context including the history of messages and function calls
         */
        export interface Context {
            /** Conversation history as a list of messages and function calls */
            messages?: Context.Messages.Item[] | undefined;
        }

        export namespace Context {
            export type Messages = Messages.Item[];

            export namespace Messages {
                /**
                 * A message here is either a conversational message or a function call
                 */
                export type Item =
                    /**
                     * Conversation text as part of the conversation history */
                    | {
                          type: "History";
                          role: "user" | "assistant" | string;
                          content: string;
                      }
                    /**
                     * Client-side or server-side function call request and response as part of the conversation history */
                    | {
                          type: "History";
                          function_calls: {
                              id: string;
                              name: string;
                              client_side: boolean;
                              arguments: string;
                              response: string;
                          }[];
                      };
            }
        }

        export interface Listen {
            provider?: Deepgram.agent.AgentV1SettingsAgentListenProvider | undefined;
        }

        export type Think = Deepgram.ThinkSettingsV1 | Deepgram.ThinkSettingsV1[];
        export type Speak = Deepgram.SpeakSettingsV1 | Deepgram.SpeakSettingsV1[];
    }
}
