// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface AgentV1Settings {
    type: "Settings";
    /** Tags to associate with the request */
    tags?: string[];
    /** To enable experimental features */
    experimental?: boolean;
    flags?: AgentV1Settings.Flags;
    /** To opt out of Deepgram Model Improvement Program */
    mip_opt_out?: boolean;
    audio: AgentV1Settings.Audio;
    agent: AgentV1Settings.Agent;
}

export namespace AgentV1Settings {
    export interface Flags {
        /** Enable or disable history message reporting */
        history?: boolean;
    }

    export interface Audio {
        /** Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality. */
        input?: Audio.Input;
        /** Audio output configuration settings */
        output?: Audio.Output;
    }

    export namespace Audio {
        /**
         * Audio input configuration settings. If omitted, defaults to encoding=linear16 and sample_rate=24000. Higher sample rates like 44100 Hz provide better audio quality.
         */
        export interface Input {
            /** Audio encoding format */
            encoding: Input.Encoding;
            /** Sample rate in Hz. Common values are 16000, 24000, 44100, 48000 */
            sample_rate: number;
        }

        export namespace Input {
            /** Audio encoding format */
            export const Encoding = {
                Linear16: "linear16",
                Linear32: "linear32",
                Flac: "flac",
                Alaw: "alaw",
                Mulaw: "mulaw",
                AmrNb: "amr-nb",
                AmrWb: "amr-wb",
                Opus: "opus",
                OggOpus: "ogg-opus",
                Speex: "speex",
                G729: "g729",
            } as const;
            export type Encoding = (typeof Encoding)[keyof typeof Encoding];
        }

        /**
         * Audio output configuration settings
         */
        export interface Output {
            /** Audio encoding format for streaming TTS output */
            encoding?: Output.Encoding;
            /** Sample rate in Hz */
            sample_rate?: number;
            /** Audio bitrate in bits per second */
            bitrate?: number;
            /** Audio container format. If omitted, defaults to 'none' */
            container?: string;
        }

        export namespace Output {
            /** Audio encoding format for streaming TTS output */
            export const Encoding = {
                Linear16: "linear16",
                Mulaw: "mulaw",
                Alaw: "alaw",
            } as const;
            export type Encoding = (typeof Encoding)[keyof typeof Encoding];
        }
    }

    export interface Agent {
        /** Agent language */
        language?: string;
        /** Conversation context including the history of messages and function calls */
        context?: Agent.Context;
        listen?: Agent.Listen;
        think?: Agent.Think;
        speak?: Agent.Speak;
        /** Optional message that agent will speak at the start */
        greeting?: string;
    }

    export namespace Agent {
        /**
         * Conversation context including the history of messages and function calls
         */
        export interface Context {
            /** Conversation history as a list of messages and function calls */
            messages?: Context.Messages.Item[];
        }

        export namespace Context {
            export type Messages = Messages.Item[];

            export namespace Messages {
                /**
                 * A message here is either a conversational message or a function call
                 */
                export type Item =
                    /**
                     * Conversation text as part of the conversation history */
                    | {
                          type: "History";
                          role: "user" | "assistant";
                          content: string;
                      }
                    /**
                     * Client-side or server-side function call request and response as part of the conversation history */
                    | {
                          type: "History";
                          function_calls: {
                              id: string;
                              name: string;
                              client_side: boolean;
                              arguments: string;
                              response: string;
                          }[];
                      };
            }
        }

        export interface Listen {
            provider?: Listen.Provider;
        }

        export namespace Listen {
            export interface Provider {
                /** Provider type for speech-to-text */
                type: "deepgram";
                /** Model to use for speech to text */
                model?: string;
                /** Prompt key-term recognition (nova-3 'en' only) */
                keyterms?: string[];
                /** Applies smart formatting to improve transcript readability (Deepgram providers only) */
                smart_format?: boolean;
            }
        }

        export interface Think {
            provider: Think.Provider;
            /** Optional for non-Deepgram LLM providers. When present, must include url field and headers object */
            endpoint?: Think.Endpoint;
            functions?: Think.Functions.Item[];
            prompt?: string;
            /** Specifies the number of characters retained in context between user messages, agent responses, and function calls. This setting is only configurable when a custom think endpoint is used */
            context_length?: Think.ContextLength;
        }

        export namespace Think {
            export type Provider =
                | {
                      type?: "open_ai" | undefined;
                      model?:
                          | (
                                | "gpt-5"
                                | "gpt-5-mini"
                                | "gpt-5-nano"
                                | "gpt-4.1"
                                | "gpt-4.1-mini"
                                | "gpt-4.1-nano"
                                | "gpt-4o"
                                | "gpt-4o-mini"
                            )
                          | undefined;
                      temperature?: number | undefined;
                  }
                | {
                      type?: "aws_bedrock" | undefined;
                      model?:
                          | ("anthropic/claude-3-5-sonnet-20240620-v1:0" | "anthropic/claude-3-5-haiku-20240307-v1:0")
                          | undefined;
                      temperature?: number | undefined;
                      credentials?:
                          | {
                                type?: ("sts" | "iam") | undefined;
                                region?: string | undefined;
                                access_key_id?: string | undefined;
                                secret_access_key?: string | undefined;
                                session_token?: string | undefined;
                            }
                          | undefined;
                  }
                | {
                      type?: "anthropic" | undefined;
                      model?: ("claude-3-5-haiku-latest" | "claude-sonnet-4-20250514") | undefined;
                      temperature?: number | undefined;
                  }
                | {
                      type?: "google" | undefined;
                      model?: ("gemini-2.0-flash" | "gemini-2.0-flash-lite" | "gemini-2.5-flash") | undefined;
                      temperature?: number | undefined;
                  }
                | {
                      type?: "groq" | undefined;
                      model?: "openai/gpt-oss-20b" | undefined;
                      temperature?: number | undefined;
                  };

            /**
             * Optional for non-Deepgram LLM providers. When present, must include url field and headers object
             */
            export interface Endpoint {
                /** Custom LLM endpoint URL */
                url?: string;
                /** Custom headers for the endpoint */
                headers?: Record<string, string>;
            }

            export type Functions = Functions.Item[];

            export namespace Functions {
                export interface Item {
                    /** Function name */
                    name?: string;
                    /** Function description */
                    description?: string;
                    /** Function parameters */
                    parameters?: Record<string, unknown>;
                    /** The Function endpoint to call. if not passed, function is called client-side */
                    endpoint?: Item.Endpoint;
                }

                export namespace Item {
                    /**
                     * The Function endpoint to call. if not passed, function is called client-side
                     */
                    export interface Endpoint {
                        /** Endpoint URL */
                        url?: string;
                        /** HTTP method */
                        method?: string;
                        headers?: Record<string, string>;
                    }
                }
            }

            /**
             * Specifies the number of characters retained in context between user messages, agent responses, and function calls. This setting is only configurable when a custom think endpoint is used
             */
            export type ContextLength = "max" | number;
        }

        export type Speak =
            | {
                  provider: Deepgram.agent.AgentV1SettingsAgentSpeakEndpointProvider;
                  endpoint?:
                      | {
                            url?: string | undefined;
                            headers?: Record<string, string> | undefined;
                        }
                      | undefined;
              }
            | {
                  provider: Deepgram.agent.AgentV1SettingsAgentSpeakOneItemProvider;
                  endpoint?:
                      | {
                            url?: string | undefined;
                            headers?: Record<string, string> | undefined;
                        }
                      | undefined;
              }[];
    }
}
