// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export type AgentV1SettingsAgentThinkProvider =
    | Deepgram.agent.AgentV1SettingsAgentThinkProvider.OpenAi
    | Deepgram.agent.AgentV1SettingsAgentThinkProvider.AwsBedrock
    | Deepgram.agent.AgentV1SettingsAgentThinkProvider.Anthropic
    | Deepgram.agent.AgentV1SettingsAgentThinkProvider.Google
    | Deepgram.agent.AgentV1SettingsAgentThinkProvider.Groq;

export namespace AgentV1SettingsAgentThinkProvider {
    export interface OpenAi {
        type: "open_ai";
        /** The REST API version for the OpenAI text-to-speech API */
        version?: "v1";
        /** OpenAI TTS model */
        model: OpenAi.Model;
        /** OpenAI voice */
        voice: OpenAi.Voice;
    }

    export namespace OpenAi {
        /** OpenAI TTS model */
        export const Model = {
            Tts1: "tts-1",
            Tts1Hd: "tts-1-hd",
        } as const;
        export type Model = (typeof Model)[keyof typeof Model];
        /** OpenAI voice */
        export const Voice = {
            Alloy: "alloy",
            Echo: "echo",
            Fable: "fable",
            Onyx: "onyx",
            Nova: "nova",
            Shimmer: "shimmer",
        } as const;
        export type Voice = (typeof Voice)[keyof typeof Voice];
    }

    export interface AwsBedrock {
        type: "aws_bedrock";
        /** AWS Bedrock model to use */
        model: AgentV1SettingsAgentThinkProviderAwsBedrock.Model;
        /** AWS Bedrock temperature (0-2) */
        temperature?: number;
        /** AWS credentials type (STS short-lived or IAM long-lived) */
        credentials?: AgentV1SettingsAgentThinkProviderAwsBedrock.Credentials;
    }

    export namespace AgentV1SettingsAgentThinkProviderAwsBedrock {
        /** AWS Bedrock model to use */
        export const Model = {
            AnthropicClaude35Sonnet20240620V10: "anthropic/claude-3-5-sonnet-20240620-v1:0",
            AnthropicClaude35Haiku20240307V10: "anthropic/claude-3-5-haiku-20240307-v1:0",
        } as const;
        export type Model = (typeof Model)[keyof typeof Model];

        /**
         * AWS credentials type (STS short-lived or IAM long-lived)
         */
        export interface Credentials {
            /** AWS credentials type (STS short-lived or IAM long-lived) */
            type?: Credentials.Type;
            /** AWS region */
            region?: string;
            /** AWS access key */
            access_key_id?: string;
            /** AWS secret access key */
            secret_access_key?: string;
            /** AWS session token (required for STS only) */
            session_token?: string;
        }

        export namespace Credentials {
            /** AWS credentials type (STS short-lived or IAM long-lived) */
            export const Type = {
                Sts: "sts",
                Iam: "iam",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }

    export interface Anthropic {
        type: "anthropic";
        /** The REST API version for the Anthropic Messages API */
        version?: "v1";
        /** Anthropic model to use */
        model: Anthropic.Model;
        /** Anthropic temperature (0-1) */
        temperature?: number;
    }

    export namespace Anthropic {
        /** Anthropic model to use */
        export const Model = {
            Claude35HaikuLatest: "claude-3-5-haiku-latest",
            ClaudeSonnet420250514: "claude-sonnet-4-20250514",
        } as const;
        export type Model = (typeof Model)[keyof typeof Model];
    }

    export interface Google {
        type: "google";
        /** The REST API version for the Google generative language API */
        version?: "v1beta";
        /** Google model to use */
        model: Google.Model;
        /** Google temperature (0-2) */
        temperature?: number;
    }

    export namespace Google {
        /** Google model to use */
        export const Model = {
            Gemini20Flash: "gemini-2.0-flash",
            Gemini20FlashLite: "gemini-2.0-flash-lite",
            Gemini25Flash: "gemini-2.5-flash",
        } as const;
        export type Model = (typeof Model)[keyof typeof Model];
    }

    export interface Groq {
        type: "groq";
        /** The REST API version for the Groq's chat completions API (mostly OpenAI-compatible) */
        version?: "v1";
        /** Groq model to use */
        model: "openai/gpt-oss-20b";
        /** Groq temperature (0-2) */
        temperature?: number;
    }
}
