// This file was auto-generated by Fern from our API Definition.

import type * as Deepgram from "../../../../../index.js";

export interface AgentV1UpdateSpeak {
    /** Message type identifier for updating the speak model */
    type: "UpdateSpeak";
    speak: AgentV1UpdateSpeak.Speak;
}

export namespace AgentV1UpdateSpeak {
    export type Speak =
        | {
              provider: Deepgram.agent.AgentV1UpdateSpeakSpeakEndpointProvider;
              endpoint?:
                  | {
                        url?: string | undefined;
                        headers?: Record<string, string> | undefined;
                    }
                  | undefined;
          }
        | {
              provider: Deepgram.agent.AgentV1UpdateSpeakSpeakOneItemProvider;
              endpoint?:
                  | {
                        url?: string | undefined;
                        headers?: Record<string, string> | undefined;
                    }
                  | undefined;
          }[];
}
