// This file was auto-generated by Fern from our API Definition.

export interface AgentV1ForceEndTurn {
    /** Message type identifier for forcing the end of the current turn */
    type: "ForceEndTurn";
}
