// This file was auto-generated by Fern from our API Definition.

export interface AgentV1CustomToThinkProvider {
    /** Message type identifier for sending a custom payload to the think provider */
    type: "__customToThinkProvider";
    content: unknown;
}
