// This file was auto-generated by Fern from our API Definition.

export interface AgentV1AgentAudioDone {
    /** Message type identifier indicating the agent has finished sending audio */
    type: "AgentAudioDone";
}
