// This file was auto-generated by Fern from our API Definition.

export interface AgentV1ConversationText {
    /** Message type identifier for conversation text */
    type: "ConversationText";
    /** Identifies who spoke the statement */
    role: AgentV1ConversationText.Role;
    /** The actual statement that was spoken */
    content: string;
    /** The language hints that were active at the time of the turn. Only present on user-role messages when the listen model is flux-general-multi. */
    languages_hinted?: string[] | undefined;
    /** Languages detected in the user's speech, sorted by word count (descending). Only present on user-role messages when the listen model is flux-general-multi. */
    languages?: string[] | undefined;
}

export namespace AgentV1ConversationText {
    /** Identifies who spoke the statement */
    export const Role = {
        User: "user",
        Assistant: "assistant",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role] | string;
}
