/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Agent } from "./api/resources/agent/client/Client.js";
import { Auth } from "./api/resources/auth/client/Client.js";
import { Listen } from "./api/resources/listen/client/Client.js";
import { Manage } from "./api/resources/manage/client/Client.js";
import { Read } from "./api/resources/read/client/Client.js";
import { SelfHosted } from "./api/resources/selfHosted/client/Client.js";
import { Speak } from "./api/resources/speak/client/Client.js";

export declare namespace DeepgramClient {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class DeepgramClient {
    protected readonly _options: DeepgramClient.Options;
    protected _agent: Agent | undefined;
    protected _auth: Auth | undefined;
    protected _listen: Listen | undefined;
    protected _manage: Manage | undefined;
    protected _read: Read | undefined;
    protected _selfHosted: SelfHosted | undefined;
    protected _speak: Speak | undefined;

    constructor(_options: DeepgramClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@deepgram/sdk",
                    "X-Fern-SDK-Version": "4.11.3",
                    "User-Agent": "@deepgram/sdk/4.11.3",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get agent(): Agent {
        return (this._agent ??= new Agent(this._options));
    }

    public get auth(): Auth {
        return (this._auth ??= new Auth(this._options));
    }

    public get listen(): Listen {
        return (this._listen ??= new Listen(this._options));
    }

    public get manage(): Manage {
        return (this._manage ??= new Manage(this._options));
    }

    public get read(): Read {
        return (this._read ??= new Read(this._options));
    }

    public get selfHosted(): SelfHosted {
        return (this._selfHosted ??= new SelfHosted(this._options));
    }

    public get speak(): Speak {
        return (this._speak ??= new Speak(this._options));
    }
}
