// This file was auto-generated by Fern from our API Definition.

import { AgentClient } from "./api/resources/agent/client/Client.js";
import { AuthClient } from "./api/resources/auth/client/Client.js";
import { ListenClient } from "./api/resources/listen/client/Client.js";
import { ManageClient } from "./api/resources/manage/client/Client.js";
import { ReadClient } from "./api/resources/read/client/Client.js";
import { SelfHostedClient } from "./api/resources/selfHosted/client/Client.js";
import { SpeakClient } from "./api/resources/speak/client/Client.js";
import { VoiceAgentClient } from "./api/resources/voiceAgent/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";

export declare namespace DeepgramClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DeepgramClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DeepgramClient.Options>;
    protected _agent: AgentClient | undefined;
    protected _auth: AuthClient | undefined;
    protected _listen: ListenClient | undefined;
    protected _manage: ManageClient | undefined;
    protected _read: ReadClient | undefined;
    protected _selfHosted: SelfHostedClient | undefined;
    protected _speak: SpeakClient | undefined;
    protected _voiceAgent: VoiceAgentClient | undefined;

    constructor(options: DeepgramClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get agent(): AgentClient {
        return (this._agent ??= new AgentClient(this._options));
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get listen(): ListenClient {
        return (this._listen ??= new ListenClient(this._options));
    }

    public get manage(): ManageClient {
        return (this._manage ??= new ManageClient(this._options));
    }

    public get read(): ReadClient {
        return (this._read ??= new ReadClient(this._options));
    }

    public get selfHosted(): SelfHostedClient {
        return (this._selfHosted ??= new SelfHostedClient(this._options));
    }

    public get speak(): SpeakClient {
        return (this._speak ??= new SpeakClient(this._options));
    }

    public get voiceAgent(): VoiceAgentClient {
        return (this._voiceAgent ??= new VoiceAgentClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl:
                    this._options.baseUrl ??
                    (async () => {
                        const env = await core.Supplier.get(this._options.environment);
                        return typeof env === "string"
                            ? env
                            : ((env as Record<string, string>)?.base ??
                                  environments.DeepgramEnvironment.Production.base);
                    }),
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
