// This file was auto-generated by Fern from our API Definition.

export interface DeepgramEnvironmentUrls {
    base: string;
    production: string;
    agent: string;
    agentRest: string;
}

export const DeepgramEnvironment = {
    Production: {
        base: "https://api.deepgram.com",
        production: "wss://api.deepgram.com",
        agent: "wss://agent.deepgram.com",
        agentRest: "https://agent.deepgram.com",
    },
} as const;

export type DeepgramEnvironment = typeof DeepgramEnvironment.Production;
