// This file was auto-generated by Fern from our API Definition.

export const DeepgramEnvironment = {
    Production: "https://api.deepgram.com",
    Agent: "https://agent.deepgram.com",
} as const;

export type DeepgramEnvironment = typeof DeepgramEnvironment.Production | typeof DeepgramEnvironment.Agent;
