// This file was auto-generated by Fern from our API Definition.

/** Method type for the request */
export const RequestsListRequestMethod = {
    Sync: "sync",
    Async: "async",
    Streaming: "streaming",
} as const;
export type RequestsListRequestMethod = (typeof RequestsListRequestMethod)[keyof typeof RequestsListRequestMethod];
