// This file was auto-generated by Fern from our API Definition.

/** Deployment type for the requests */
export const RequestsListRequestDeployment = {
    Hosted: "hosted",
    Beta: "beta",
    SelfHosted: "self-hosted",
} as const;
export type RequestsListRequestDeployment =
    | (typeof RequestsListRequestDeployment)[keyof typeof RequestsListRequestDeployment]
    | string;
