/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RequestsListRequestStatus = "succeeded" | "failed";
export const RequestsListRequestStatus = {
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
