/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as Deepgram from "../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../errors/index.js";
import { Keys } from "../resources/keys/client/Client.js";
import { Members } from "../resources/members/client/Client.js";
import { Models } from "../resources/models/client/Client.js";
import { Requests } from "../resources/requests/client/Client.js";
import { Usage } from "../resources/usage/client/Client.js";
import { Billing } from "../resources/billing/client/Client.js";

export declare namespace Projects {
    export interface Options {
        environment?: core.Supplier<environments.DeepgramEnvironment | environments.DeepgramEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Projects {
    protected readonly _options: Projects.Options;
    protected _keys: Keys | undefined;
    protected _members: Members | undefined;
    protected _models: Models | undefined;
    protected _requests: Requests | undefined;
    protected _usage: Usage | undefined;
    protected _billing: Billing | undefined;

    constructor(_options: Projects.Options = {}) {
        this._options = _options;
    }

    public get keys(): Keys {
        return (this._keys ??= new Keys(this._options));
    }

    public get members(): Members {
        return (this._members ??= new Members(this._options));
    }

    public get models(): Models {
        return (this._models ??= new Models(this._options));
    }

    public get requests(): Requests {
        return (this._requests ??= new Requests(this._options));
    }

    public get usage(): Usage {
        return (this._usage ??= new Usage(this._options));
    }

    public get billing(): Billing {
        return (this._billing ??= new Billing(this._options));
    }

    /**
     * Retrieves basic information about the projects associated with the API key
     *
     * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.list()
     */
    public list(requestOptions?: Projects.RequestOptions): core.HttpResponsePromise<Deepgram.ListProjectsV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: Projects.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.ListProjectsV1Response>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                "v1/projects",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.ListProjectsV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling GET /v1/projects.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieves information about the specified project
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Deepgram.manage.v1.ProjectsGetRequest} request
     * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.get("123456-7890-1234-5678-901234", {
     *         limit: 1.1,
     *         page: 1.1
     *     })
     */
    public get(
        projectId: string,
        request: Deepgram.manage.v1.ProjectsGetRequest = {},
        requestOptions?: Projects.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.GetProjectV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__get(projectId, request, requestOptions));
    }

    private async __get(
        projectId: string,
        request: Deepgram.manage.v1.ProjectsGetRequest = {},
        requestOptions?: Projects.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.GetProjectV1Response>> {
        const { limit, page } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.GetProjectV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling GET /v1/projects/{project_id}.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes the specified project
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.delete("123456-7890-1234-5678-901234")
     */
    public delete(
        projectId: string,
        requestOptions?: Projects.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.DeleteProjectV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__delete(projectId, requestOptions));
    }

    private async __delete(
        projectId: string,
        requestOptions?: Projects.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.DeleteProjectV1Response>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.DeleteProjectV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/projects/{project_id}.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates the name or other properties of an existing project
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Deepgram.manage.v1.UpdateProjectV1Request} request
     * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.update("123456-7890-1234-5678-901234")
     */
    public update(
        projectId: string,
        request: Deepgram.manage.v1.UpdateProjectV1Request = {},
        requestOptions?: Projects.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.UpdateProjectV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__update(projectId, request, requestOptions));
    }

    private async __update(
        projectId: string,
        request: Deepgram.manage.v1.UpdateProjectV1Request = {},
        requestOptions?: Projects.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.UpdateProjectV1Response>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.UpdateProjectV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError("Timeout exceeded when calling PATCH /v1/projects/{project_id}.");
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Removes the authenticated account from the specific project
     *
     * @param {string} projectId - The unique identifier of the project
     * @param {Projects.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Deepgram.BadRequestError}
     *
     * @example
     *     await client.manage.v1.projects.leave("123456-7890-1234-5678-901234")
     */
    public leave(
        projectId: string,
        requestOptions?: Projects.RequestOptions,
    ): core.HttpResponsePromise<Deepgram.LeaveProjectV1Response> {
        return core.HttpResponsePromise.fromPromise(this.__leave(projectId, requestOptions));
    }

    private async __leave(
        projectId: string,
        requestOptions?: Projects.RequestOptions,
    ): Promise<core.WithRawResponse<Deepgram.LeaveProjectV1Response>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.DeepgramEnvironment.Production
                    ).base,
                `v1/projects/${encodeURIComponent(projectId)}/leave`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Deepgram.LeaveProjectV1Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Deepgram.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.DeepgramError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DeepgramError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.DeepgramTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/projects/{project_id}/leave.",
                );
            case "unknown":
                throw new errors.DeepgramError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = (await core.Supplier.get(this._options.apiKey)) ?? process?.env["DEEPGRAM_API_KEY"];
        return { Authorization: `Token ${apiKeyValue}` };
    }
}
