// This file was auto-generated by Fern from our API Definition.

import * as Deepgram from "../../../../../../src/api/index";
import { DeepgramClient } from "../../../../../../src/Client";
import { mockServerPool } from "../../../../../mock-server/MockServerPool";

describe("InvitesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { invites: [{ email: "email", scope: "scope" }] };
        server
            .mockEndpoint()
            .get("/v1/projects/123456-7890-1234-5678-901234/invites")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.members.invites.list("123456-7890-1234-5678-901234");
        expect(response).toEqual({
            invites: [
                {
                    email: "email",
                    scope: "scope",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/invites")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.members.invites.list("project_id");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = { email: "email", scope: "scope" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/v1/projects/123456-7890-1234-5678-901234/invites")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.members.invites.create("123456-7890-1234-5678-901234", {
            email: "email",
            scope: "scope",
        });
        expect(response).toEqual({
            message: "message",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });
        const rawRequestBody = { email: "email", scope: "scope" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/invites")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.members.invites.create("project_id", {
                email: "email",
                scope: "scope",
            });
        }).rejects.toThrow(Deepgram.BadRequestError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/v1/projects/123456-7890-1234-5678-901234/invites/john.doe%40example.com")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.manage.v1.projects.members.invites.delete(
            "123456-7890-1234-5678-901234",
            "john.doe@example.com",
        );
        expect(response).toEqual({
            message: "message",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DeepgramClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl, agent: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/projects/project_id/invites/email")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.manage.v1.projects.members.invites.delete("project_id", "email");
        }).rejects.toThrow(Deepgram.BadRequestError);
    });
});
