name: Browser Build Test

on:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "webpack.config.js"
      - "tsconfig*.json"
  workflow_dispatch:

jobs:
  browser-build-test:
    name: Test Browser Builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm run build

      - name: Test with Vite
        run: |
          cd /tmp
          npm create vite@latest test-app -- --template react-ts -y
          cd test-app
          npm install
          npm install $GITHUB_WORKSPACE
          echo "import { createClient } from '@deepgram/sdk';" > src/test.ts
          echo "const client = createClient('test-key');" >> src/test.ts
          npm run build

      - name: Test with Create React App
        run: |
          cd /tmp
          npx create-react-app test-cra --template typescript
          cd test-cra
          npm install $GITHUB_WORKSPACE
          echo "import { createClient } from '@deepgram/sdk';" > src/test.ts
          echo "const client = createClient('test-key');" >> src/test.ts
          npm run build

      - name: Test with plain webpack
        run: |
          cd /tmp
          mkdir webpack-test && cd webpack-test
          npm init -y
          npm install webpack webpack-cli typescript ts-loader
          npm install $GITHUB_WORKSPACE
          echo "import { createClient } from '@deepgram/sdk';" > index.ts
          echo "const client = createClient('test-key');" >> index.ts
          echo "module.exports = { entry: './index.ts', module: { rules: [{ test: /\.ts$/, use: 'ts-loader' }] } };" > webpack.config.js
          npx webpack --mode production
