name: Changelog Log

on:
  push:
    branches: [main]
    paths:
      - "**/CHANGELOG*.md"
      - "**/changelog*.md"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Send changelog to webhook
        uses: lukeocodes/changelog-log@changelog-log-v0.1.7
        with:
          webhook_url: ${{ secrets.CHANGELOG_WEBHOOK_URL }}
          webhook_headers_json: '{"Content-Type":"application/json","X-DX-Logs-Key":"${{ secrets.CHANGELOG_SECRET }}"}'
          extra_body_json: '{"route":"changelog-javascript"}'
