name: Check - All linters, etc
on:
  push:
    branches:
      - main
      - release-*
    tags-ignore:
      - "**"

jobs:
  build:
    name: Change to Main/Release Branch
    # Only run this job if we're in the main repo, not a fork.
    if: github.repository == 'deepgram/deepgram-js-sdk'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code by commit
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        id: go

      - name: Ensure dependencies installed
        shell: bash
        run: |
          make ensure-deps

      - name: Run all checks
        shell: bash
        run: |
          make check
