name: CI

on:
  pull_request:
    branches:
      - main
      - next
      - rc
      - beta
      - alpha
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".prettierrc"
      - "**/*ignore"
  push:
    branches:
      - main
      - next
      - rc
      - beta
      - alpha
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".prettierrc"
      - "**/*ignore"

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["18"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      # TODO: Fix JS/TS linting issues (too big of a change to be in scope of this PR)
      # - name: Lint JS/TS
      #   run: |
      #     npm run lint

      - name: Lint YAML
        run: |
          npm run lint:yaml

      - name: Lint MD
        run: |
          npm run lint:md

      - name: Run tests
        run: |
          npm clean-install
          npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
