name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --no-optional=false

      - name: Compile
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --no-optional=false

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist/

      - name: Test
        run: make test

      - name: Test ESM
        run: make test-esm

  release-please:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          target-branch: ${{ github.ref_name }}

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --no-optional=false

      - name: Build
        run: make build

      - name: Publish to npm
        run: npm publish --provenance --access public
