name: Release

on:
  push:
    branches:
      - main
      - next
      - rc
      - beta
      - alpha
      - release/*
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ["20"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci
          npm run build

      - name: Create a release
        run: npx semantic-release
        with:
          branches:
            [
              "+([0-9])?(.{+([0-9]),x}).x",
              "master",
              "main",
              "next",
              "next-major",
              { name: "beta", prerelease: true },
              { name: "alpha", prerelease: true },
              { name: "release/*", prerelease: true },
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
